http4k-core/src/main/kotlin/org/http4k/core/cookie/CookieExtensions.kt, http4k-core/src/test/kotlin/org/http4k/core/cookie/CookieTest.kt
This adds an optional parameter to set the domain when invalidating a cookie. When there's an existing cookie with a domain set, invalidating it with `Response.invalidateCookie(name: String)` won't work because the response cookie this adds doesn't include the domain.
=> add ability to invalidate a cookie that has domain set

http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoute.kt, http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoutingHttpHandler.kt, http4k-contract/src/main/kotlin/org/http4k/contract/OpenApi.kt, http4k-contract/src/main/kotlin/org/http4k/contract/deprecated.kt, http4k-contract/src/main/kotlin/org/http4k/contract/extensions.kt, http4k-contract/src/main/kotlin/org/http4k/contract/routeMeta.kt, http4k-contract/src/main/kotlin/org/http4k/contract/routeSpec.kt, http4k-contract/src/main/kotlin/org/http4k/util/Appendable.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRouteTest.kt, http4k-contract/src/test/kotlin/org/http4k/contract/test.kt, src/docs/cookbook/typesafe_http_contracts/example.kt, src/docs/guide/modules/contracts/example.kt
The current version of the contracts API involves quite a lot of infix functions and this isn't very good in terms of discoverability, since the various calls are split. This PR reimplements the "meta" section of the API, so now instead of declaring:
```Path -> Service Constructor Fn (-> optional Meta block)```
... the new call chain is:
```Path -> (optional Meta block ->) Service Constructor Fn```
The new API also uses a Groovy-style DSL builder, which you can see examples of at: https://kotlinlang.org/docs/reference/type-safe-builders.html
Overall this change makes the API much more consistent with the rest of http4k. The old API is still present, but deprecated.
=> Contract API reimplementation

http4k-core/src/main/kotlin/org/http4k/core/ResponseCacheExt.kt, http4k-core/src/main/kotlin/org/http4k/filter/CachingFilters.kt, http4k-core/src/test/kotlin/org/http4k/core/ResponseCacheExtTest.kt
Hey,
Saw you had an Hacktoberfest issue so thought i'd give it a punt.  Not sure if the location/filename of the ResponseCacheExt.kt is where you'd like it to be.  Also not sure if you'd want to allow the chaining conflicting headers (e.g. Response(OK).public().private() etc.) but left that up to the user.
Let me know what you think
Andy
=> #13 Create extension methods for Response to add caching headers

src/docs/guide/modules/core/index.md
First example uses an `app` val which is not defined.
=> doc - fix first example in core guide

http4k-contract/src/main/kotlin/org/http4k/contract/OpenApi.kt, http4k-contract/src/main/kotlin/org/http4k/contract/routeMeta.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt, http4k-contract/src/test/resources/org/http4k/contract/OpenApiTest.json
This adds support for adding an `operationId` field to paths for Swagger definitions. This field allows developers to customize the naming of methods when auto-generating API clients in Swagger. For example, if an endpoint `GET /echo/{message}` has an operationId `echoMessage`, the method name in Swagger's client will be `echoMessage` vs `getEchoMessage`
=> Add support for operationId to Swagger

http4k-contract/src/main/kotlin/org/http4k/contract/extensions.kt, http4k-contract/src/main/kotlin/org/http4k/contract/routeSpec.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRouteTest.kt
I ran into this issue when I was trying to implement an api with HTTP4k and really need the support for at least 6 path parameters. I added 10 in the hopes of being more future proof.
=> Updated to handle up to 10 path parameters in a contract route.

http4k-core/src/main/kotlin/org/http4k/core/UriTemplate.kt
When attempting to create a `router` on Android, we hit a fatal `java.util.regex.PatternSyntaxException`:
```
Process: org.example.test, PID: 17588
java.lang.ExceptionInInitializerError
at org.http4k.routing.PathMethod.to(routing.kt:40)
at org.example.test.MainActivity.onCreate(MainActivity.kt:25)
at android.app.Activity.performCreate(Activity.java:6684)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
at android.os.Handler.dispatchMessage(Handler.java:102)
at …
```
=> add extra escaping to URI_TEMPLATE_FORMAT to make router work on Android

build.gradle, http4k-format-jsoniter/build.gradle, http4k-format-jsoniter/src/main/kotlin/org/http4k/format/JsonIter.kt, http4k-format-jsoniter/src/test/kotlin/org/http4k/format/JsonIterTest.kt
Motivation: JsonIter has a nice API, has lazy evaluation, and is faster than most other JSON libs.
(See benchmarks at https://github.com/fabienrenaud/java-json-benchmark)
I could simply add JsonIter to my project and use it, but then Http4K lib itself would still use another JSON lib, so I would end up having 2 JSON library dependencies.
By having a JsonIter module, I can have only 1 JSON dependency, and as an added bonus, Http4K will use a faster JSON library ;)
=> Http4k JsonIter JSON support - http://jsoniter.com/

http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoutingHttpHandler.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRoutingHttpHandlerTest.kt, http4k-core/src/main/kotlin/org/http4k/core/HttpTransaction.kt, http4k-core/src/main/kotlin/org/http4k/core/UriTemplate.kt, http4k-core/src/main/kotlin/org/http4k/lens/header.kt, http4k-core/src/main/kotlin/org/http4k/routing/internal.kt, http4k-core/src/main/kotlin/org/http4k/routing/routing.kt, http4k-core/src/test/kotlin/org/http4k/core/HttpTransactionTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/lens/PathTest.kt, http4k-core/src/test/kotlin/org/http4k/routing/RoutingTest.kt
This solves the issue with setting and removing the header. We now use polymorphism.
The only thing I'm not sure about is if we should have a RoutedHttpMessage sealed class to sit over the top. This would abstract the xUriTemplate and remove a line in the HttpTransaction.
=> replacing x-uri-template header with RoutedResponse and RoutedRequest

http4k-client-websocket/src/main/kotlin/org/http4k/client/WebsocketClient.kt
Symptom: WS clients close immediately with a connection timeout when given a timeout like `30` (interpreted as milliseconds).
=> Fix conversion of timeout to millis for websocket client

http4k-contract/src/main/kotlin/org/http4k/util/JsonSchema.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt, http4k-contract/src/test/kotlin/org/http4k/util/JsonToJsonSchemaTest.kt, http4k-contract/src/test/resources/org/http4k/contract/OpenApiTest.json, http4k-contract/src/test/resources/org/http4k/util/JsonSchema_definitions.json, http4k-core/src/main/kotlin/org/http4k/format/Json.kt, http4k-core/src/test/kotlin/org/http4k/format/JsonContract.kt, http4k-format-argo/src/main/kotlin/org/http4k/format/Argo.kt, http4k-format-gson/src/main/kotlin/org/http4k/format/Gson.kt, http4k-format-jackson/src/main/kotlin/org/http4k/format/Jackson.kt
For example objects in a schema, this PR will populate the example field of OpenAPI so that end users will see an example request rather than simply `"string"` or `0`.
=> OpenApi example values

http4k-server-netty/src/main/kotlin/org/http4k/server/Netty.kt
This provides a specific factory for server channels rather than relying on the reflection one internally, this improves compatibility with GraalVM
=> Get rid of reflection netty factory

http4k-core/src/main/kotlin/org/http4k/filter/ZipkinTraces.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/RequestTracingTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ZipkinTracesTest.kt
As per the [Zipkin spec](https://github.com/openzipkin/b3-propagation) there's a standardised sampling decision header that can be used to inform clients as to whether they should sample the current request. This adds support for the capture and propagation of this header, allowing recording filters to decide whether or not to sample based on an upstream decision.
Note that we default to "sample" so as to maintain backwards compatibility.
=> Add support for propagation of the Zipkin x-b3-sampled header

http4k-core/src/main/kotlin/org/http4k/filter/ClientFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt
When the port isn't null, it gets appended to the host name on the 'Host' header. Fixes #162
=> SetHostFrom: Port should be added to header when non-null

http4k-testing-webdriver/src/main/kotlin/org/http4k/webdriver/Http4kWebDriver.kt, http4k-testing-webdriver/src/test/kotlin/org/http4k/webdriver/Http4kWebDriverTest.kt
In master if you do:
`driver.navigate().to(Uri.of("http://slashdot.org")) `
then you'll find that to is resolved to an extension method to construct pairs in the Kotlin standard library which will produce code with no effect, which could be confusing.
=> allow navigation to Uri objects

http4k-testing-webdriver/src/main/kotlin/org/http4k/webdriver/Http4kWebDriver.kt, http4k-testing-webdriver/src/main/kotlin/org/http4k/webdriver/JSoupElementFinder.kt, http4k-testing-webdriver/src/main/kotlin/org/http4k/webdriver/JSoupWebElement.kt, http4k-testing-webdriver/src/main/kotlin/org/http4k/webdriver/Page.kt, http4k-testing-webdriver/src/test/kotlin/org/http4k/webdriver/Http4kWebDriverTest.kt, http4k-testing-webdriver/src/test/kotlin/org/http4k/webdriver/JSoupElementFinderTest.kt, http4k-testing-webdriver/src/test/kotlin/org/http4k/webdriver/JSoupWebElementTest.kt, http4k-testing-webdriver/src/test/kotlin/org/http4k/webdriver/PageTest.kt, http4k-testing-webdriver/src/test/resources/test.html
I found a form in the wild which had an action attribute with no value. This change tests and handles that case in the WebDriver. I've followed the pattern of having callback parameters from the Element that can be used with the driver, rather than keep a WebDriver reference in all SoupElements. What's unfortunately touches more files than I'd like.
I can extend the pattern of counting the number of times the HTTPHandler gets called into the other test cases if you like.
=> allow empty action items

http4k-core/src/main/kotlin/org/http4k/filter/ClientFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientCookiesTest.kt
so that parsed expiry dates are not affected by system timezone (since Clock.instant() is always in UTC)
=> Use UTC when checking cookie expiry

http4k-testing-webdriver/src/main/kotlin/org/http4k/webdriver/JSoupWebElement.kt, http4k-testing-webdriver/src/test/resources/test.html
Hey folks,
Noticed this small bug today: if a checkbox is `checked` without a value to the `checked` attribute then the webdriver thinks it's not checked.
So
```html
<input type="checkbox" checked="yup"</input>
```
is checked, but
```html
<input type="checkbox" checked</input>
```
isn't
Bit of digging discovered that `getAttribute` for "checked" should be returning "true" when there is a `checked` attribute and `null` otherwise - that's at least how I read the docs on the JSoup interface.
And so we've added a list of attributes which are 'boolean', and we've added that logic to `getAttribute`.
Hope that makes sense!
=> WebDriver - checkboxes' 'checked' attribute does not require a value

http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
The current GZip filter is an all-or-nothing affair. This extends it so that you can give it a set of content-types which will restrict the responses for which GZipping will be performed. This allows you to ensure that previously compressed content such as PNGs will not be recompressed.
I also fixed a Javadoc, as you lot are hacks who do too much copy & paste ;-)
=> Add filter allowing Gzipping based on an allowed set of content types

http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
As discussed with Ivan on Slack, we've noticed some issues with the way that CORS is handled in http4k when multiple values are involved for allow-origin header. This pull request hopefully fixes that issue.
=> handle multiple allow-origin values

http4k-core/src/main/kotlin/org/http4k/filter/CachingFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/CachingFiltersTest.kt
FallbackCacheControl claims it will include a default value for "Cache-Control", "Expires" and "Vary" headers when they are not present in the response. However it is actually duplicating the existing values when these headers are already present in the response. This PR fixes that.
=> Preventing FallbackCacheControl from duplicating existing headers

http4k-core/src/main/kotlin/org/http4k/routing/internal.kt, http4k-core/src/test/kotlin/org/http4k/routing/StaticPrefixRoutingTest.kt, http4k-core/src/test/resources/bar/bar-xyz.html, http4k-core/src/test/resources/bar/bar.html, http4k-core/src/test/resources/bar/bar/bar-xyz.html, http4k-core/src/test/resources/bar/bar/bar.html, http4k-core/src/test/resources/bar/bar/index.html, http4k-core/src/test/resources/bar/index.html
Hello here
I found a case when paths are not translated properly
For example request `GET /bar/bar-xyz.html` to `routes("/bar" bind static(Classpath("bar")))` was translated into`/-xyz.html`
=> Issue with prefixes in static routing

http4k-core/src/main/kotlin/org/http4k/core/Status.kt
We're using this in our code by defining it ourselves.
Seems a legitimate code (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) so adding it here.
=> Added missing Status 426, "Upgrade Required".

http4k-contract/src/main/kotlin/org/http4k/util/JsonSchema.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt
=> Allow null values in examples used for schema generation in contracts

http4k-core/build.gradle, http4k-core/src/main/kotlin/org/http4k/client/JavaHttpClient.kt, http4k-core/src/test/kotlin/org/http4k/client/AbstractHttpClientContract.kt, http4k-core/src/test/kotlin/org/http4k/client/HttpClientContract.kt, http4k-core/src/test/kotlin/org/http4k/client/JavaHttpClientTest.kt
This fixes an issue where a null pointer exception is thrown when an empty body is returned for error responses, using the JavaHttpClient calling a server backed by Jetty.
Specifically, the error stream can be null, which means the code extracting the body will fail with a null pointer exception.
This change will handle that case by returning an empty input stream if the underlying stream is null.
=> Handle null response stream in Java HTTP client

http4k-serverless-lambda/src/main/java/org/http4k/serverless/lambda/ApiGatewayProxyRequest.java
Trying to invoke a lambda locally using serverless throws this exception:
```
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.serverless.InvokeBridge.invoke(InvokeBridge.java:93)
at com.serverless.InvokeBridge.<init>(InvokeBridge.java:39)
at com.serverless.InvokeBridge.main(InvokeBridge.java:150)
Caused by: java.lang.IllegalStateException: httpMethod must not be null
at org.http4k.serverless.lambda.LambdaFunctionKt.asHttp4k(LambdaFunction.kt:25)
at org.http4k.serverless.lambda.LambdaFunction.handle(LambdaFunction.kt:19)
... 7 more
```
Values …
=> serverless - Allow handlers to be called locally

build.gradle
When importing the latest http4k in Intellij on Windows it fails with message:
> Incorrect dir property, only Unix based path allowed.
This is happening in the dokka task because the dir property in the linkmapping is being passed a Windows file path, but since dokka 0.9.18 this isn't allowed (verified by trying 0.9.17 and the project imported fine).
I believe Replacing whatever file separator the OS uses with "/" will always result in a valid Unix path for the projectDir in this case.
Only tested on my Windows machine since it's such a small change but I'm happy to spin up different OS and verify there too if need be.
=> Ensure dir for linkmapping in dokka task is a unix path.

http4k-multipart/src/main/kotlin/org/http4k/multipart/StreamingMultipartFormParts.kt, http4k-multipart/src/test/kotlin/org/http4k/multipart/StreamingMultipartFormHappyTests.kt
We build our mobile client with react-native. We use plain XMLHttpRequest and FormData to create file upload requests. We found that http4k failed to parse lowercase multipart header field names generated by XMLHttpRequest.
=> Made the multipart header parser case-insensitive.

build.gradle, buildSrc/src/main/kotlin/Versions.kt
I've configured dokka to target JDK 9 (later versions not possible due to bug, see commit for more details), and also added links to many of http4k dependencies' javadocs, so that they are usable from the api docs.
=> Improve api documentation: Link to JDK 9 and dependencies' javadocs

http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v2/OpenApi2.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v2/OpenApi2Test.kt, http4k-contract/src/test/resources/org/http4k/contract/openapi/v2/OpenApi2Test.renders root path correctly when bind path and root path match.approved
When generating OpenAPI2 descriptions where the root and base path are the same, an invalid description is generated.
For example:
```kotlin
val router = "/" bind contract {
routes += "/" bindContract Method.GET to { Response(Status.OK) }
descriptionPath = "/docs"
}
```
Would generate swagger as follows:
```json
{
"swagger": "2.0",
"info": {
"title": "title",
"version": "1.2",
"description": "module description"
},
"basePath": "/",
"paths": {
"": {
"get": {
"operationId": "get"
}
}
}
}
```
Which is invalid as empty strings for `#path` URIs are not allowed. This can be tested by running the output of the API through a swagger validator as follows:
```sh
$ npm install swagger-cli -g
$ swagger-cli validate example-http4k-swagger.json
```
=> Fix invalid OpenAPI2 when root and base path match

http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoutingHttpHandler.kt, http4k-contract/src/main/kotlin/org/http4k/contract/extensions.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt, http4k-contract/src/test/resources/org/http4k/contract/openapi/v2/OpenApi2Test.when enabled renders description including its own path.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.when enabled renders description including its own path.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3Test.when enabled renders description including its own path.approved, http4k-contract/src/test/resources/org/http4k/contract/simple/SimpleJsonTest.when enabled renders description including its own path.approved
Google Cloud Endpoints (GCE) will only make an endpoint publicly accessible if it has a path directive in the OpenAPI description. But by default http4k-contract does not include the contract path in the OpenAPI description.
This means hosted Swagger documentation is inaccessible unless we manually re-format the results of the contract route.
This change adds an optional directive to the contract DSL that adds the description path to the OpenAPI description, allowing it to be accessed when deployed in GCE.
=> Optionally include description path in description

http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v2/OpenApi2SecurityRenderer.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v2/OpenApi2Test.kt, http4k-contract/src/test/resources/org/http4k/contract/openapi/v2/OpenApi2Test.renders Google Cloud Endpoints OAuth2.approved
This ticket adds support for Google Cloud Endpoints (GCE) OAuth2 as defined in this document:
https://cloud.google.com/endpoints/docs/openapi/authenticating-users-custom
Note: by default the GCE Extensible Service Proxy handles authentication, so the new GCE Security implementation sets a NOOP authentication filter by default.
=> Add support for Google Cloud Endpoints OAuth2

http4k-security-oauth/src/main/kotlin/org/http4k/security/AccessTokenFetcher.kt, http4k-security-oauth/src/test/kotlin/org/http4k/security/AccessTokenFetcherTest.kt
When the `Content-Type` of the response is `application/json` instead of `application/json;charset=utf-8` http4k fails to parse the body as JSON. When no charset is specified, the default is utf-8.
This problem came to light when I was using http4k to authenticate to Keycloak.
=> Parse access token response as json when content-type is missing encoding directive

http4k-format-jackson/src/main/kotlin/org/http4k/format/ConfigurableJackson.kt, http4k-format-jackson/src/test/kotlin/org/http4k/format/JacksonTest.kt
By porting the [Spring MVC's Jackson serialization logic](https://github.com/spring-projects/spring-framework/blob/9c17eb59a4312a9787b23ebaea3bff6e95f3657c/spring-web/src/main/java/org/springframework/http/converter/json/AbstractJackson2HttpMessageConverter.java#L250)
=> Refix writer lookup for jackson

http4k-core/src/main/kotlin/org/http4k/filter/ZipkinTraces.kt, http4k-core/src/test/kotlin/org/http4k/filter/RequestTracingTest.kt
This adds method to expose, and allow overwriting, the current Zipkin trace data.
> "Why, this is madness! Why would you break encapsulation in such a way?"
I'm glad you asked. We have a case where we use a thread-pool to query various services in parallel. We need to ensure that these threads have a copy of the current trace data to ensure that we can reconstruct the trace. As such, we need to copy the data across on task initialisation, in a similar manner to the provided test.
=> Add method to allow copying of trace information to child worker threads

http4k-core/src/main/kotlin/org/http4k/filter/ClientFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/RequestFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ext.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/GzipBodyTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
This PR introduces a parameter to the various GZip filters, allowing then to be used with streaming operations, as opposed to the current implementation which relies on in-memory transformations.
This has a number of benefits:
* We can support the GZip en/decoding of resources requiring streaming
* It should reduce memory usage
It also has a number of drawbacks, primarily that you can only consume the stream a single time. As such, it has been introduced as a variation of behaviour, to allow both existing users and convenient applications (e.g. testing) to retain the current behaviour.
And in any case, better devs than I have buggered up streaming code, so it's definitely safer to introduce it as an opt-in option, rather than a mandated replacement.
`GZippingInputStream` is derived from …
=> Introduce support for GZipping response streams

.editorconfig
Minor addition - `editorconfig` file, since your edits suggest you're using a lower continuation indent than standard, and I'm all for keeping diffs simple.
=> Add editorconfig file to ensure contributed code uses the non-standard continuation indent

http4k-core/src/main/kotlin/org/http4k/filter/RequestFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ext.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/GzipBodyTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/RequestFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
These changes fix two issues described in #338:
* both in-memory and streaming Gzip filters would apply a `content-encoding` header of `gzip` even if no transformation had taken place. In particular this led to us sending requests with absent/empty bodies with an incorrect `content-encoding`. We now only apply the header when compression has taken place.
* the streaming decompressor would try and deserialise anything with a `content-encoding` of `gzip`. If the body was empty then Java's `GZIPInputStream` would throw an `EOFException`. We no longer attempt to decompress empty streams.
As an aside, whoever came up with providing a useless default impl of `available()` on `InputStream` is a twit and I don't like them. Being unable to rely on that made this a chunk more painful.
=> Gzip fixes

http4k-core/src/main/kotlin/org/http4k/filter/ClientFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt
This fixes one bug - that the GZip client filters never set the `accept-encoding` header on the outgoing requests, and hence cannot expect to receive gzipped content in the response.
It also adds a new client filter, `AcceptGZip`, which will only set the header and handle gzipped responses, unlike `ClientFilters.GZip` which will also Gzip the request (which is pretty specialised, as you cannot determine if the server will request it and need to implement 415 handling to be safe).
=> Add missing `accept-encoding` header; add remote-gzip-only client filter

http4k-core/src/main/kotlin/org/http4k/core/cookie/Cookie.kt, http4k-core/src/test/kotlin/org/http4k/core/cookie/CookieTest.kt, http4k-testing-hamkrest/src/main/kotlin/org/http4k/hamkrest/cookie.kt, http4k-testing-hamkrest/src/test/kotlin/org/http4k/hamkrest/CookieMatchersTest.kt
Add the SameSite attribute to Cookies using an enum for the current possible values. SameSite is a modeled here as a nullable attribute without any default value. Although many browsers currently treat a missing SameSite attribute as `Lax` for first-party cookies, this change does not set a default value since some browsers inconsistently handle values of `None` for third-party cookies, notably Safari on Mac OS X 10.14 and iOS 12. To support "SameSite=None" behavior on these browsers, the SameSite attribute should be omitted.
References:
- web.dev: SameSite Cookies Explained https://web.dev/samesite-cookies-explained/
- web.dev: SameSite Cookie Recipes https://web.dev/samesite-cookie-recipes/
- List of incompatible SameSite=None clients …
=> Support SameSite Cookies #340

http4k-testing-servirtium/src/main/kotlin/org/http4k/traffic/extensions.kt, http4k-testing-servirtium/src/test/kotlin/org/http4k/junit/junitExtensionIntegrationTests.kt, http4k-testing-servirtium/src/test/kotlin/org/http4k/traffic/ReplayExtensionTests.kt
When receive more interactions then there are in interaction script, do not report `expected "" but received $actual ` because it leads to false believe that something is wrong with parsing of interaction script and empty input is expected.
Instead report this case as `Have $interactions interactions in the script but called $count times. Unexpected interaction`
Another problem arise when `ResilienceFilters.RetryFailures` is used and mistake is made in interaction script. Error message would say "Interaction 99 failed" if retry is configured for 100 retries. I had just single interaction in my script and it took deep dive into the library to understand where 99 is coming from.
I had to duplicate requests().zip(responses()) to get interactions count because `Sequence` is used. Perhaps it …
=> Improve error message when too many interactions

http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoute.kt, http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoutingHttpHandler.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRouteTest.kt, http4k-core/src/main/kotlin/org/http4k/routing/internal.kt, http4k-core/src/main/kotlin/org/http4k/routing/routing.kt, http4k-core/src/test/kotlin/org/http4k/routing/RoutingHttpHandlerContract.kt, http4k-core/src/test/kotlin/org/http4k/routing/RoutingTest.kt, http4k-core/src/test/kotlin/org/http4k/routing/StaticRoutingHttpHandlerTest.kt, http4k-incubator/src/main/kotlin/org/http4k/routing/experimental/ResourceLoaders.kt, http4k-incubator/src/main/kotlin/org/http4k/routing/experimental/StaticRoutingHttpHandler.kt, http4k-incubator/src/test/kotlin/org/http4k/routing/experimental/ResourceLoaderContract.kt, http4k-incubator/src/test/kotlin/org/http4k/routing/experimental/ResourceLoadingHandlerTest.kt, http4k-testing-chaos/src/test/kotlin/org/http4k/chaos/ChaosEngineTest.kt
At present the route-matching is boolean, i.e. a route either matches or it doesn't. This results in a 404 being served for all unmatched requests.
This PR changes the routing so that it returns a match object, allowing us to differentiate on match failures. At this point it represents three states - `matched`, `path matched, method mismatched`, `unmatched`. The result is that we can now support returning 405 where the path is matched but the supported methods differ.
This is a breaking change, as the `Router.match` signature is now `fun match(request: Request): RouterMatchResult`, rather than returning `HttpHandler?`.
Given the scope of this change there's no way I'm merging it without a sanity check 😄
=> Support method not allowed

http4k-template-pebble/src/main/kotlin/org/http4k/template/PebbleTemplates.kt
Pebble templates, when loaded from a compiled JAR, do not load from non-root directories.
When using `ClassLoader.getResource`, any path is assumed to be from the root of the JAR - so passing in, say, "templates", would resolve to "templates" at the root of the JAR. This is different to the resolution behaviour from `Class.getResource`, which resolves relative to the class - getting a resource from the root of the JAR in that case would be done with a preceding slash.
Pebble's ClasspathLoader uses the prefix, then the expected separator if not present (which in the case of internal JAR file resolution is a forward slash, so this is hardcoded), followed by the template name, followed by the template name, followed by the suffix. 
This means that the prefix, if one wished to load templates …
=> Fix non-root pebble templates when using CachingClasspath from a compiled JAR

http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/BasicAuthenticationTest.kt
Currently this filter throws an exception which results in an internal server error when the given base64 string is invalid (cut of byte sequence, invalid characters...).
This is bad since it's not a server but a client error. After this change, it will lead to an UNAUTHORIZED when a client submits an invalid base64 string.
=> Fix BasicAuth server filter to not throw an exception on invalid base64 input

http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoutingHttpHandler.kt, http4k-contract/src/main/kotlin/org/http4k/contract/extensions.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRoutingHttpHandlerTest.kt
In our use case we needed to have the swagger JSON under authorised access. I wasn't able achieve that with the current public http4k APIs. Hence this MR.
Peace! .)
=> Add support for securing the API description endpoint

http4k-cloudnative/src/main/kotlin/org/http4k/cloudnative/env/Environment.kt, http4k-cloudnative/src/test/kotlin/org/http4k/cloudnative/env/EnvironmentKeyTest.kt, http4k-cloudnative/src/test/kotlin/org/http4k/cloudnative/env/EnvironmentTest.kt
As soon as we add to an existing `MapEnvironment` we lose custom separators, as they aren't propagated to the new object.
=> Fix separator propagation when adding values to an existing MapEnvironment

buildSrc/src/main/kotlin/Versions.kt, http4k-core/src/main/kotlin/org/http4k/core/http.kt, http4k-core/src/main/kotlin/org/http4k/servlet/Http4kServletAdapter.kt, http4k-core/src/test/kotlin/org/http4k/core/RequestTest.kt, http4k-server-apache/src/main/kotlin/org/http4k/server/ApacheServer.kt, http4k-server-jetty/src/main/kotlin/org/http4k/server/Http4kWebSocketListener.kt, http4k-server-ktorcio/src/main/kotlin/org/http4k/server/KtorCIO.kt, http4k-server-ktornetty/src/main/kotlin/org/http4k/server/KtorNetty.kt, http4k-server-netty/src/main/kotlin/org/http4k/server/Netty.kt, http4k-server-ratpack/src/main/kotlin/org/http4k/server/Ratpack.kt, http4k-server-undertow/src/main/kotlin/org/http4k/server/Undertow.kt
closes #120
Hi! Thank you for http4k. I really like it.
I implemented support for source address and port in Request interface.
Added two tests for them, but servers have been tested manually (but I can try to write junit tests, if there's need in them).
A few moments:
* What will be default values, when address and port isn't specified? "" and -1 or null/null?
* Ratpack: for IPv6 loopback source address is 0:0:0:0:0:0:0:1%0. Just for your information.
* KtorNetty/KtorCIO: I couldn't find any information about retrieving source port.
Also. I'm getting errors in some tests and I don't understand how I could affect them, for example, in `src/docs/tutorials/tdding_http4k/_1/tests.kt` (IllegalStateException: server.uri must not be null)
Looks like the root cause is in this line: …
=> Implementation of remote address and port in Request interface

buildSrc/src/main/kotlin/Versions.kt, http4k-core/src/main/kotlin/org/http4k/core/http.kt, http4k-core/src/main/kotlin/org/http4k/server/SunHttp.kt, http4k-core/src/main/kotlin/org/http4k/servlet/Http4kServletAdapter.kt, http4k-core/src/test/kotlin/org/http4k/core/RequestTest.kt, http4k-core/src/test/kotlin/org/http4k/server/ServerContract.kt, http4k-server-apache/src/main/kotlin/org/http4k/server/ApacheServer.kt, http4k-server-jetty/src/main/kotlin/org/http4k/server/Http4kWebSocketListener.kt, http4k-server-ktorcio/src/main/kotlin/org/http4k/server/KtorCIO.kt, http4k-server-ktorcio/src/test/kotlin/org/http4k/server/KtorCIOTest.kt, http4k-server-ktornetty/src/main/kotlin/org/http4k/server/KtorNetty.kt, http4k-server-ktornetty/src/test/kotlin/org/http4k/server/KtorNettyTest.kt, http4k-server-netty/src/main/kotlin/org/http4k/server/Netty.kt, http4k-server-ratpack/src/main/kotlin/org/http4k/server/Ratpack.kt, http4k-server-undertow/src/main/kotlin/org/http4k/server/Undertow.kt
Closes #120
Based on #434. Simplified the API in `Request` and added tests for it in `ServerContract`.
It's worth noticing that this capability is inherently limited:
1. It depends on what the server implementation retrieves from the client socket. While most servers will bring an IP address, Ktor returns the client hostname.
2. It has very limited use if the server sits behind any proxy that masks client connections.
=> Expose client address and port in Request

http4k-core/src/main/kotlin/org/http4k/core/http.kt, http4k-core/src/main/kotlin/org/http4k/servlet/Http4kServletAdapter.kt, http4k-core/src/test/kotlin/org/http4k/server/ServerContract.kt, http4k-server-jetty/src/test/kotlin/org/http4k/server/JettyTest.kt, http4k-server-ktorcio/src/main/kotlin/org/http4k/server/KtorCIO.kt, http4k-server-ktorcio/src/test/kotlin/org/http4k/server/KtorCIOTest.kt, http4k-server-undertow/src/main/kotlin/org/http4k/server/Undertow.kt, http4k-server-undertow/src/test/kotlin/org/http4k/server/UndertowTest.kt
This PR adds a `scheme` property to the `RequestSource` object, allowing the inference of HTTPS use where HTTPS is handled directly on the server. Do note that not all servers expose this (e.g. Netty), therefore it's only supported by a subset of servers, returning `null` if not supported.
=> Add request scheme to RequestSource, where available

http4k-core/src/main/kotlin/org/http4k/core/cookie/CookieExtensions.kt, http4k-core/src/test/kotlin/org/http4k/core/cookie/CookieTest.kt
HTTP/2 [allows multiple `Cookie` headers](https://tools.ietf.org/html/rfc7540#section-8.1.2.5). This changes the `cookies()` extension method to deal with this, rather than just grabbing the first one.
=> Added support for multiple "cookie" headers

http4k-core/src/main/kotlin/org/http4k/server/SunHttp.kt
Included in this MR:
- **Refactoring to allow reuse of the handler** 
Done in a very similar way to the Undertow handler and fixed a potential issue with HttpExchange not getting closed in the rare circumstance that `sendResponseHeaders(500, 0)` inside the `catch` block fails.
- **Enable parallel processing of requests**
Opted for using a work-stealing pool aka (ForkJoinPool) because it doesn't require us to set a fixed limit of threads and instead allows us to set the targeted parallelism which by default is `getRuntime().availableProcessors()`.
- **Set backlog of the server socket to 1000**
This is the same limit that is applied explicitly or through the defaults in the case of Netty, Undertow and ApacheServer
Closes #465
=> Change defaults of SunHttp server and enable reuse of the HttpExchangeHandler

http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/AutoJsonToJsonSchema.kt, http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/FieldRetrieval.kt, http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/jacksonExt.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/FieldRetrievalTest.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/JacksonFieldMetadataRetrievalStrategyTest.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/JacksonJsonNamingAnnotatedTest.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/JacksonJsonPropertyAnnotatedTest.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/SimpleLookupTest.kt, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.can override definition id for a map.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.can override definition id for a raw map.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.can override definition id.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for custom json mapping.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for field with description.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for freeform map field.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for holder with generic list.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for list of enums.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for map field.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for nested arbitrary objects.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for non-string-keyed map field.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for raw map field.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for recursive objects.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for top level generic list.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for top level list.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for various json primitives.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for when cannot find entry.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.renders as expected.approved
Description can be added by annotating the class field with `@JsonPropertyDescription`. Fixes https://github.com/http4k/http4k/issues/464
=> Make it possible to add description to OpenApi schema field

src/docs/css/main.css, src/mkdocs.yml
Why:
I find usefull to be able to give someone a precise link to a specific part of a page of the documentation.
What:
The modifcation adds a ¶ at the end of pages' titles when the mouse is over it that is a link to that specific title.
How:
I activated the mkdocs toc/permalinks extenesion and added some css.
Result:
=> Documentation: permalink added at the end of pages titles

http4k-metrics-micrometer/src/main/kotlin/org/http4k/filter/micrometerExtensions.kt
This line is logging directly to console on every request. As its not using logging libraries took me a while to track down where it's coming from.
=> Remove log spam

http4k-core/src/main/resources/META-INF/org/http4k/core/mime.types
In order to be able serve markdown files for static resources.
=> Add markdown content type to the mime types

http4k-core/src/main/resources/META-INF/org/http4k/core/mime.types
No big deal but realised afterwards that there's no need for the uppercase version as in code is done a toLowerCase.
=> Markdown content type

src/docs/css/site.css
On the first PR I added these css in the main.css that was overridden. 
In fact I guess it was not the right place to put them, site.css seems more adequate.
Now the ending ¶ at the end of titles will no longer be visible if the mouse is not over the title.
=> fix: css for hiding headers link when mouse not over it

http4k-client/apache-async/src/main/kotlin/org/http4k/client/ApacheAsyncClient.kt, http4k-client/apache-async/src/test/kotlin/org/http4k/client/ApacheAsyncClientTest.kt
I noticed that the `ApacheAsyncClient` requires a different kind of initialisation compared to the `Apache4AsyncClient`. Before supplying a client to the constructor of the ApacheAsyncClient it needs to be started with the function `client.start()`. This additional call is however not needed when using the `Apache4AsyncClient`.
Although it not a big deal to call the additional start method, but it just caught my attention and that the configuration is not similar. I analysed the source code and discovered that the `Apache4AsyncClient` calls internally `if (!client.isRunning) client.start()` on line number 34. This part is missing within the `ApacheAsyncClient`, but it is easy to include.
=> Start ApacheAsyncClient by default if not started yet

src/docs/cookbook/typesafe_http_contracts/index.md
see 
```
val contract = contract {
renderer = OpenApi3(ApiInfo("my great api", "v1.0"), Jackson)
descriptionPath = "/docs/swagger.json"
```
=> Fixed wrong swagger.json path (cookbook)

http4k-security-oauth/src/main/kotlin/org/http4k/security/AccessTokenFetcher.kt, http4k-security-oauth/src/test/kotlin/org/http4k/security/AccessTokenFetcherTest.kt
We were ignoring fields like the refresh token.
=> AccessTokenFetcher initializes all AccessToken fields.

http4k-core/src/main/kotlin/org/http4k/filter/ClientFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt
A special case of redirection should be taken into account for See_Other (303).
See_Other should be followed by a GET and as per RFC a GET with body has no defined semantics. See below:
https://tools.ietf.org/html/rfc7231#page-24
_A payload within a GET request message has no defined semantics;
sending a payload body on a GET request might cause some existing
implementations to reject the request._
This PR intends to strips out payload coming from a POST requests that is followed by a GET
=> See_Other (303) is a special case of redirection.

http4k-core/src/main/kotlin/org/http4k/core/HttpTransaction.kt, http4k-core/src/main/kotlin/org/http4k/routing/extensions.kt, http4k-core/src/main/kotlin/org/http4k/routing/messages.kt, http4k-core/src/test/kotlin/org/http4k/core/HttpTransactionTest.kt, http4k-core/src/test/kotlin/org/http4k/routing/RoutedMessageTest.kt
This PR adds interfaces `RequestWithRoute` and `ResponseWithRoute` to `RoutedRequest` and `RoutedResponse`. This allows extending the capabilities of the `RoutedRequest / RoutedResponse` via delegates such as:
```
class ExtendedRequest(val delegate: RoutedRequest) : RequestWithRoute by delegate {
...
}
```
Without these interfaces, extensions such as Request.path would fail to identify that such request is a wrapper around a RoutedRequest that supports path extraction.
=> Added interfaces to allow extending RoutedRequest and RoutedResponse via delegates

http4k-aws/src/main/kotlin/org/http4k/filter/awsExtensions.kt, http4k-aws/src/test/kotlin/org/http4k/aws/AwsAuthClientFilterTest.kt
Hello!
This PR is a quick fix for custom domain usage of the module `http4k-connect` which uses `http4k-aws`: https://github.com/http4k/http4k-connect/issues/17
Unfortunately, I cannot try with a real `amazonaws.com` s3 service since I don't have any at my disposal, but I tried this fix on our on-premise internal installation and it works.
=> fix(http4k-aws): add x-amz-content-sha256 to SignedHeaders

http4k-core/src/main/kotlin/org/http4k/filter/ConditionalFilter.kt, http4k-template/core/src/test/kotlin/org/http4k/filter/ConditionalFilterTest.kt
Fixes #595 
This will enable the http4k framework to run the filter conditionally.
I've implemented the basic functions  `thenIf` and `thenIfNot` which accept a `condition` and `filter` and run them accordingly. If this looks good ok to the reviewers, i can go ahead and implement some more basic convenience methods are  for common cases such as URL matching
- thenIfPathStartsWith
- thenIfPathNotStartsWith
- thenIfPathMatches
- thenIfPathNotMatches
=> #595 implementing thenIf and thenIfNot extensions to have conditional filter

src/docs/cookbook/nestable_routes/index.md
Variables in paths are covered in the docs but I didn't find anything about restricting them via Regex. I wanted to clarify and add a few examples for people who aren't familiar with Regex's or who might be coming from a framework (Flask, Bottle) which has pre-defined types. Please feel free to edit/modify any of the docs or examples to better match with http4k's existing documentation style. Or, if this is already covered, replace the whole thing with a link.
=> update "nestable routes" docs

http4k-core/src/main/kotlin/org/http4k/KotlinExtensions.kt, http4k-core/src/main/kotlin/org/http4k/core/http.kt, http4k-core/src/test/kotlin/org/http4k/core/BodyTest.kt
Fixes a bug in MemoryBody: when a ByteBuffer was created with a nonzero offset and/or length shorter than the size of the underlying array, the entire array was used as the content of the body.
=> MemoryBody takes offset and limit of ByteBuffer into account.

http4k-core/src/main/kotlin/org/http4k/core/UriTemplate.kt
In `UriTemplate` the function `trimSlashes()` is defined as a public extension on String. However, it should only be accessible inside `UriTemplate`
=> trimSlashes should not be accessible outside UriTemplate

http4k-security/digest/src/main/kotlin/org/http4k/security/digest/ParameterizedHeader.kt, http4k-security/digest/src/test/kotlin/org/http4k/security/digest/DigestChallengeTest.kt
Ran into this issue while trying to adapt the client filter for authorization over RTSP.  Still good to be resilient to minor issues like this in any case.
=> be resilient to extra space in Digest challenge header value

http4k-opentelemetry/src/main/kotlin/org/http4k/filter/tracingFiltersOpenTelemetryExtensions.kt, http4k-opentelemetry/src/test/kotlin/org/http4k/filter/OpenTelemetryTracingTest.kt
I'm sure this won't be a surprise, but I'm an idiot. The span creation mutator now takes the request so you can actally respond to elements of the request (e.g. headers), rather than just spinning in the void 🤦
=> SpanCreationMutator now takes the request, so you can respond to request attributes

http4k-aws/src/main/kotlin/org/http4k/aws/AwsCanonicalRequest.kt, http4k-aws/src/test/kotlin/org/http4k/aws/AwsCanonicalRequestTest.kt
Hi @daviddenton,
Simple PR to fix an incorrect signature generated on requests where no query value is needed.
e.g., GET /?lifecycle on the bucket
"lifecycle=" instead of "lifecycle=null" 
https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLifecycleConfiguration.html
=> Set the query parameter to empty string if it's value is null, instead of "null"

src/docs/guide/reference/graphql/example.kt, versions.properties
Downgrade graphql-java to 16.2 for compatibility with graphql-kotlin-schema-generator 4.1.1
Wait for 5.0.0 of graphql-kotlin-schema-generator or if they release a fix upgrade to 4.1.1 before going back to 17.0
=> Downgrade graphql-java and fix Graphql reference example

src/docs/guide/tutorials/your_first_http4k_app/index.md
While working through the `Your first http4k app` tutorial, I found a few areas that might benefit from an update or addition and wanted to contribute back to this really helpful resource. These updates included:
- Including the command to utilize the http4k project wizard, as an alternative to using the web version (I had trouble locating an example for this, but figured it out from the http4k command options)
- Updating two incorrect paths (`/main` to `/test`)
- Adding the `/pong` endpoint manually in Step 6. Since the tutorial already led the reader to pointing the client at the `/pong` endpoint to see the 404, I thought it was a great opportunity to have the reader manually add the endpoint in (especially since the initial one was pre-populated by the project wizard
=> Update 'Your first http4k app' tutorial

http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt, http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3ApiRenderer.kt, http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/jacksonExt.kt, http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/model.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/OpenApi3AutoTest.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/OpenApi3ServersDefaultTest.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/OpenApi3Test.kt, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.renders as expected.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.when enabled renders description including its own path.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3ServersDefaultTest.renders as expected.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3ServersDefaultTest.when enabled renders description including its own path.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3Test.renders as expected.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3Test.when enabled renders description including its own path.approved, http4k-testing/chaos/src/test/resources/org/http4k/chaos/ChaosEngineTest.chaos API is available as openapi JSON.approved, src/docs/guide/howto/integrate_with_openapi/example.kt
This is my attempt at finishing off @zsambek's https://github.com/http4k/http4k/pull/510. There were some outstanding issues with https://github.com/http4k/http4k/pull/510 this PR hopefully resolves:
- rename ServerObject to ApiServer
- remove wildcard imports
- update examples
- add spec-compliant default
- change url type from `String` to `Uri`
I was uncertain on some formatting around when and where to make newlines for longer lines, let me know if there are any offensive formatting errors.
=> Servers in contracts

http4k-format/core/src/main/kotlin/org/http4k/format/AutoMarshallingXml.kt, http4k-format/jackson-xml/src/main/kotlin/org/http4k/format/ConfgurableJacksonXml.kt, http4k-format/jackson-xml/src/test/kotlin/org/http4k/format/JacksonXmlTest.kt
This adds an `autoBody` method for a `ConfigurableJacksonXml` instance.  This is useful for creating a `Lens` for a custom xml marshaller.
It also lets you override the `ContentType` of `JacksonXml`'s `Body.auto` method.
=> add autoBody for ConfigurableJacksonXml

http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/jacksonExt.kt, http4k-contract/src/test/kotlin/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.kt, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for object from sealed class.approved
I noticed that if we are using `object` for contract route, it will throw an exception like below when http4k tries to generate the swagger.json file.
Please let me know if I have done it correctly.
```
java.util.NoSuchElementException: List is empty.
at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:196)
at org.http4k.contract.openapi.v3.JacksonFieldMetadataRetrievalStrategy.findPropertyDescription(jacksonExt.kt:74)
at org.http4k.contract.openapi.v3.JacksonFieldMetadataRetrievalStrategy.invoke(jacksonExt.kt:71)
at org.http4k.contract.openapi.v3.JacksonFieldMetadataRetrievalStrategy.invoke(jacksonExt.kt:69)
at org.http4k.contract.openapi.v3.SimpleLookup.invoke(FieldRetrieval.kt:40)
at …
```
=> OpenApiV3 object serialization fix

http4k-core/src/main/resources/META-INF/org/http4k/core/mime.types
I can't see a reason why the woff2 format wouldn't be supported out-of-the-box. It's widely supported and has much better compression than woff. See browser support here: https://caniuse.com/woff2
=> The woff2 font format is now widely supported. https://caniuse.com/woff2

http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoute.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRouteTest.kt, http4k-core/src/main/kotlin/org/http4k/core/Uri.kt, http4k-core/src/main/kotlin/org/http4k/core/UriTemplate.kt, http4k-core/src/main/kotlin/org/http4k/lens/path.kt, http4k-core/src/test/kotlin/org/http4k/core/UriTemplateTest.kt, http4k-core/src/test/kotlin/org/http4k/core/UriTest.kt, http4k-core/src/test/kotlin/org/http4k/lens/PathTest.kt, src/docs/guide/reference/core/RoutingTest.kt
See [appendix A (https://www.ietf.org/rfc/rfc3986.txt)](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A) for details about valid path segments. In summary the spec indicates that a valid path segment can contain:
```
segment       = *pchar
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
pct-encoded   = "%" HEXDIG HEXDIG
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
/ "*" / "+" / "," / ";" / "="
```
The implementation can probably be optimised but the PathTest.kt tests should now capture the specification more accurately and `toPathSegmentEncoded` / `toPathSegmentDecoded` are used to encode/decode path segments.
This will change the current path encoding behaviour allowing the characters above, although …
=> Fixed URLPathSegment encoding/decoding based on RFC 3986

http4k-core/src/test/kotlin/org/http4k/server/ServerContract.kt, http4k-server/netty/src/main/kotlin/org/http4k/server/Netty.kt
I have noticed that the Netty implementation does not respect connection keep-alive and the reason is because `HttpServerKeepAliveHandler` from Netty disables keep-alive whenever the content-length is unknown: https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerKeepAliveHandler.java#L115
So I reimplemented `Http4kChannelHandler` to differentiate between the streaming and non-streaming case.
=> fix: Keep-alive for Netty when not streaming

http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
Added ContentDispositionAttachment Server Filter to add response header based on the request path.
By default all extensions are selected, including paths with no extension.
If no path is present, the filename will be set to "unnamed".
Fixes #445
=> Added ContentDispositionAttachment server filter

http4k-multipart/src/main/kotlin/org/http4k/core/MultipartFormBody.kt
Working as server to handle file upload
Now the disk cache can only be cleaned using deleteOnExit(). That means keep all the temp files until restart. But server is normally keep running without restart. 
The pull is simply put the disk cache path into parameters so we can provide the cache path and clean the cache ourselves when each request is finished.
=> add disk cache path to MultipartFormBody.from() parameters

README.md, http4k-format/jackson-csv/build.gradle.kts, http4k-format/jackson-csv/src/main/kotlin/org/http4k/format/ConfigurableJacksonCsv.kt, http4k-format/jackson-csv/src/main/kotlin/org/http4k/format/JacksonCsv.kt, http4k-format/jackson-csv/src/test/kotlin/org/http4k/format/jacksonCsvTests.kt, settings.gradle.kts, versions.properties
Closes #718.
I was unable to add `AutoMarshalling` support.  The crux of the problem centers around `abstract fun asFormatString(input: Any): String`, which does not reify the type information required to build a `CsvSchema`.  Perhaps this could be accomplished later with reflection, but it would be redoing work that the module already does, given the necessary information.
=> Add jackson csv module

http4k-core/src/main/kotlin/org/http4k/filter/CachingFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/CachingFiltersTest.kt
This PR removes empty directive values in FallbackCacheControl.
I noticed this when testing this in my codebase with zero durations for `stale-while-revalidate` and `stale-if-error`, that the `Cache-Control` header value generates something like `public, max-age=10, , `.
=> Fix header rendering for effectively empty directive values for FallbackCacheControl

http4k-core/src/main/kotlin/org/http4k/lens/BiDiMapping.kt, http4k-core/src/test/kotlin/org/http4k/lens/BiDiLensSpecTest.kt
Relates to #721 
Java locales cannot parse ISO language codes, but will happily return an empty `Locale` object, which can lead to confusion.  If accepted, this lens validation will only accept locales where a language was detected, and this updated test will formalize the notion that ISO format language codes are not supported.
=> Throw a lens failure if a valid locale was not parsed

http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/BasicAuthenticationTest.kt
Previously the server filter would truncate any colon and everything after from an incoming password
=> Fix ServerFilters.BasicAuth handling of passwords containing colons

http4k-client/fuel/src/test/kotlin/org/http4k/client/FuelStreamingTest.kt, http4k-client/fuel/src/test/kotlin/org/http4k/client/FuelTest.kt, http4k-core/src/main/kotlin/org/http4k/client/JavaHttpClient.kt, http4k-core/src/test/kotlin/org/http4k/client/HttpClientContract.kt, http4k-core/src/test/kotlin/org/http4k/client/JavaHttpClientTest.kt
Note that, although I suggested a receiver function in issue 728, I noticed that the JettyClient had a similar solution using a function `(JettyRequest) -> JettyRequest`, so I followed that example.
Also note that I enabled the `socket timeouts are converted into 504` test-function.
=> Fix #728: Add requestModifier param to JavaHttpClient

http4k-metrics-micrometer/src/main/kotlin/org/http4k/filter/micrometerExtensions.kt
This is enabling percentiles for Micrometer request timer as documented here: https://micrometer.io/docs/registry/datadog
=> feat: Enable publishPercentileHistogram for Micrometer request timer

http4k-core/build.gradle.kts, http4k-core/src/main/kotlin/org/http4k/filter/CachingFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/CachingFiltersTest.kt
Resolves https://github.com/http4k/http4k/issues/735?
hi @daviddenton, here's a quick fix for #735. I'm not sure what you mean by trailers, and as you note the performance will be bad for large response bodies, so I can understand why this shouldn't be merged. I'll leave it as a draft.
Anyway - at least the tests are useful!
=> #735 use whole message body for etag hash

http4k-security/digest/src/main/kotlin/org/http4k/security/digest/ParameterizedHeader.kt, http4k-security/digest/src/test/kotlin/org/http4k/security/digest/DigestChallengeTest.kt
I don't know why some devices think they can put an `=` in a nonce, but this fix will allow us to correctly parse the challenge.
=> Support parsing digest challenge where nonce has an '='

http4k-core/src/main/kotlin/org/http4k/core/Parameters.kt, http4k-core/src/main/kotlin/org/http4k/core/Uri.kt, http4k-core/src/test/kotlin/org/http4k/core/ParametersTest.kt, http4k-core/src/test/kotlin/org/http4k/core/UriTest.kt, http4k-security/oauth/src/test/kotlin/org/http4k/security/oauth/server/AuthRequestWithRequestAuthRequestExtractorTest.kt
- Add `queryParametersEncoded` extension to Uri to encode only parameter values
- :bug: Change `split("=")` to `split("=", limit=2)` to deal with parameter values that contain `=`
=> Add `queryParametersEncoded` + query param value split bug fix

.github/workflows/create_github_release.yaml, .github/workflows/release_site.yaml, .github/workflows/send_to_slack.yaml, .github/workflows/tweet_release.yaml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

http4k-core/src/test/kotlin/org/http4k/security/RefreshingCredentialsProviderTest.kt
There is an edge case where the calls for second refresh and chasing refresh are already done before test asserts counter for only second refresh.
Co-authored-by: mandyvuong <mandyvuong@gmail.com>
=> Refreshing Credentials Provider test improvement

http4k-multipart/src/main/kotlin/org/http4k/core/MultipartFormBody.kt, http4k-multipart/src/test/kotlin/org/http4k/core/MultipartFormBodyTest.kt
If the charset was included in the `Content-Type` header then it would end up using that as the boundary instead of the actual defined boundary.
This is my first contribution to http4k so if there is something I missed let me know!
=> Fix multipart upload failure if charset is included in content type

http4k-realtime-core/src/main/kotlin/org/http4k/testing/TestWsClient.kt, http4k-realtime-core/src/test/kotlin/org/http4k/websocket/WsClientTest.kt
Guarding against this by checking if the sequence `hasNext` is all well and good, but I think we should be able to iterate without fear.  For Example, this would throw `NoSuchElementException` if the client had no messages.
```kotlin
for (message in client.received()) {
// do stuff
}
```
=> Do not throw exception when iteration over empty TestWsClient.received sequence

src/docs/guide/howto/use_auto_content_negotiation/index.md
The intended example code is linked just below, so I think we can just remove the link, rather than fix.
=> remove incorrect and redundant doc link

CONTRIBUTING.md
Fixes a link which is currently broken:
=> fix Sponsor Us! link

http4k-multipart/src/main/kotlin/org/http4k/core/MultipartFormBody.kt, http4k-multipart/src/main/kotlin/org/http4k/multipart/DiskLocation.kt, http4k-multipart/src/main/kotlin/org/http4k/multipart/MultipartFormParser.kt, http4k-multipart/src/main/kotlin/org/http4k/multipart/Part.kt, http4k-multipart/src/test/kotlin/org/http4k/multipart/MultipartFormParserTest.kt
When uploading a file through a multipart form, we want to keep the temp file around for async virus scanning. However, in the following piece of code, the file is deleted upon JVM exit:
```kotlin
private fun writeToDisk(part: StreamingPart, bytes: ByteArray, length: Int) =
File.createTempFile(part.fileName ?: UUID.randomUUID().toString()
+ "-", ".tmp", temporaryFileDirectory).apply {
deleteOnExit()
FileOutputStream(this).apply {
write(bytes, 0, length)
use { part.inputStream.copyTo(it, writeToDiskThreshold) }
}
}
```
with the `deleteOnExit()` call.
We want to keep the file around even when the JVM exits (we're running on k8s so pods can always be killed).
This PR uses a flag that is passed from MultipartFormBody.from to the MultipartFormParser indicating to delete (or not) the temp file, …
=> Allow for keeping temporary multiparts around.

src/docs/guide/howto/moshi_lite/MoshiLite.kt
This minor addition should make it more clear what the difference is when building a "lite" version.
=> minor moshi-lite doc improvement

http4k-contract/src/main/kotlin/org/http4k/contract/PathSegments.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRouteTest.kt
Hello !
When using contracts, there is a bug when parsing parameters and passing them to the handler.
For example, if you have a route like this `"somePrefix" / Path.of("value")`, when matching `/somePrefix/somePrefixInValue`, the prefix will be removed from the value.
This PR is fixing this bug by trimming only the first occurrence when matching the uri.
=> fix: avoid altering path params

http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
Allow caching of cors preflight checks as described [here](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) by letting CorsPolicy set an access-control-max-age header.
=> Allow access-control-max-age header to be set from cors policy

http4k-core/src/main/kotlin/org/http4k/core/parser.kt, http4k-core/src/test/kotlin/org/http4k/core/HttpMessageAsStringTest.kt
I've discovered 2 issues preventing me from accurately parsing messages as they are received.
**Header values with optional leading whitespace**
The MDN specification implies that leading whitespace for header values is optional.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
**Body line-breaks not being preserved**
=> HTTP Message Parser fixes

http4k-format/argo/src/main/kotlin/org/http4k/format/Argo.kt, http4k-format/core/src/test/kotlin/org/http4k/format/JsonContract.kt, http4k-format/gson/src/main/kotlin/org/http4k/format/ConfigurableGson.kt, http4k-format/moshi/src/main/kotlin/org/http4k/format/ConfigurableMoshi.kt
OpenApi generation currently relies on the `Json.text(value: NODE): String` method to produce something usable for all primitive `NODE` types.  Not all of the `Json` implementations support this, so this new test and associated fixes will standardize the expected behaviour; baselined by Jackson's capabilities.
=> standardize behaviour of json text method

http4k-format/core/src/test/kotlin/org/http4k/format/AutoMarshallingContract.kt, http4k-format/core/src/test/kotlin/org/http4k/format/AutoMarshallingJsonContract.kt, http4k-format/jackson-yaml/src/test/kotlin/org/http4k/format/jacksonYamlTests.kt, http4k-format/jackson/src/test/kotlin/org/http4k/format/jacksonJsonTests.kt, http4k-format/klaxon/src/test/kotlin/org/http4k/format/klaxonJsonTests.kt, http4k-format/kotlinx-serialization/src/main/kotlin/org/http4k/format/ConfigurableKotlinxSerialization.kt, http4k-format/kotlinx-serialization/src/main/kotlin/org/http4k/format/KotlinxSerialization.kt, http4k-format/kotlinx-serialization/src/test/kotlin/org/http4k/format/KotlinxSerializationAutoTest.kt, http4k-format/moshi-yaml/src/main/kotlin/org/http4k/format/ConfigurableMoshiYaml.kt, http4k-format/moshi-yaml/src/test/kotlin/org/http4k/format/moshiYamlTests.kt
This might be enough to use `KotlinxSerialization` with an `OpenApi3Renderer`. 
I wasn't bothered enough to make it work for klaxon 🤷
=> Standardize AutoMarshalling roundtrip of arbitrary collections

http4k-contract/src/main/kotlin/org/http4k/contract/ui/SwaggerUi.kt, http4k-contract/src/main/resources/org/http4k/contract/ui/public/index.html, http4k-contract/src/test/resources/org/http4k/contract/ui/SwaggerUiTest.can serve swagger ui.approved, http4k-graphql/src/main/resources/org/http4k/routing/public/index.html, http4k-graphql/src/test/resources/org/http4k/routing/GraphQLExtensionsTest.can serve playground.approved
- chore(deps): upgrade `swagger-ui` from 4.15.5 to 4.17.0
- chore(deps): Use HTTPS for embedded resources where possible
- chore(deps): use [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) for `swagger-ui` & `graphql-playground-react`
- feat(swagger-ui): add options for queryConfigEnabled and tryItOutEnabled
=> Misc SwaggerUI updates

http4k-contract/src/main/kotlin/org/http4k/contract/openapi/OpenAPIJackson.kt
Useful for adding your `values4k` mappings to the precanned OpenApiJackson
=> Make OpenApiJackson customizable

CHANGELOG.md, http4k-core/src/main/kotlin/org/http4k/filter/ClientFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/Gzip.kt, http4k-core/src/main/kotlin/org/http4k/filter/RequestFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
[Breaking] Allow setting of compression level on GZip filter in both Streaming and Memory mode
To fix change from GzipCompressionMode.Memory/Streaming to GzipCompressionMode.Memory()/Streaming()
=> GZip compression level

http4k-core/src/main/kotlin/org/http4k/core/cookie/Cookie.kt, http4k-core/src/test/kotlin/org/http4k/core/cookie/CookieTest.kt
I saw an all lowercase `Lax` on google.com
=> Allow SameSite cookie attributes in lowercase and caps

http4k-incubator/src/main/kotlin/org/http4k/routing/experimental/FileResource.kt
=> Truncate file resource timestamp to seconds. #916

http4k-server/websocket/src/main/kotlin/org/http4k/server/websocket/JavaWebSocket.kt
If any WebSocket events are sent (such as a close) during the `WsHandler` invocation, it would result in an NPE and potentially kill the server.  This fix attempts to tackle the problem from two directions:
1. Register the `PushPullAdaptingWebSocket` before processing the upgrade request
2. If the `PushPullAdaptingWebSocket` hasn't been registered, gracefully avoid an NPE
=> Gracefully handle JavaWebSocket events when http4k adapter not yet registered

http4k-serverless/lambda/src/main/kotlin/org/http4k/format/SNSEventAdapter.kt, http4k-serverless/lambda/src/test/kotlin/org/http4k/format/AwsLambdaMoshiTest.kt, http4k-serverless/lambda/src/test/resources/org/http4k/format/AwsLambdaMoshiTest.SNS event - read null subject.approved
If the SNS event json has a `null` `Subject` value, the deserializer fails with an exception.  This does not occur if the property is missing.  This update will make that property null-safe.
The standard approval workflow does not work for this test.  We want to assert we can properly read a hand-crafted JSON file, rather than compare some output to a JSON file.  Please let me know if there's a better way to do this than what I've done.
=> read sns event with null Subject value

http4k-aws/src/main/kotlin/org/http4k/aws/AwsCanonicalRequest.kt, http4k-aws/src/test/kotlin/org/http4k/aws/AwsCanonicalRequestTest.kt
Fixes #947
https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html#create-canonical-request
The duplicate header issue is solved by grouping header values before sorting.
I turn it to a `Map<Header key, List<Header value>>` before sorting headers, then join the list of values with `,`.
=> Fix bug where spaces are not deduplicated. Merge duplicated headers

http4k-format/kondor-json/src/main/kotlin/org/http4k/format/KondorJson.kt, versions.properties
v2 included a breaking change to improve the rendering logic, with configurable json styles instead of predefined methods. This change also enables us to remove some custom rendering logic in KondorJson.
=> Update kondor-json to 2.0.0 and remove custom render logic

http4k-contract/jsonschema/src/main/kotlin/org/http4k/contract/jsonschema/v3/jacksonExt.kt, http4k-contract/openapi/src/test/kotlin/org/http4k/contract/openapi/v3/JacksonFieldMetadataRetrievalStrategyTest.kt
Fixes #750
When using `kotlinx.serialization` `@Serializable` for data classes in conjuction with the Jackson OpenApi generator, http4k will fail to pick up annotations on data classes.
Here is an example data class with `@Serializable`:
It will generate/compile code like this:
That `Deprecated` constructor is a hidden and generated constructor.
When http4k tries to find annotations, this one is being selected instead of the original constructor.
Scan all constructors instead of just the first.
I used sequence, so we don't crawl all constructors needlessly, it should only go one-by-one until a description is found.
A test case has been added.
I use a class like this:
which tries to emulate the `@Serializable` class.
The compiled code looks like 
.
I didn't find any resources or commands …
=> Scan all constructors for parameter descriptions

http4k-format/kondor-json/src/main/kotlin/org/http4k/format/KondorJson.kt, http4k-format/kondor-json/src/test/kotlin/org/http4k/format/KondorJsonAutoMarshallingJsonTest.kt
This PR adds the ability to create auto body lenses directly from JsonConverters, instead of going through a KondonJson instance, which is useful when there is only one converter involved.
=> JsonConverter extension methods to create auto body lenses directly

http4k-server/apache4/build.gradle.kts
A transitive vulnerability was found in the latest httpcomponents httpcore.  Overriding the transitive dependency should protect http4k.
https://devhub.checkmarx.com/cve-details/Cxeb68d52e-5509/
=> upgrade compromised commons-codec version

http4k-testing/webdriver/src/main/kotlin/org/http4k/webdriver/JSoupWebElement.kt, http4k-testing/webdriver/src/test/kotlin/org/http4k/webdriver/JSoupWebElementTest.kt
This PR allows the http4k webdriver to simulate radio buttons:
- Clicking on a selected radio input leaves the radio input selected
- Clicking on a radio input clears any other radio inputs in the same radio group
=> Improve support for radio buttons and radio groups in the http4k-testing-webdriver

src/docs/guide/reference/templating/index.md
This PR addresses the documentation changes to reflect the fact that Pebble templates will require a `model.` prefix to access the underlying model for the view.
=> Update documentation to reflect Pebble model binding

http4k-testing/webdriver/src/main/kotlin/org/http4k/webdriver/Http4kWebDriver.kt, http4k-testing/webdriver/src/test/kotlin/org/http4k/webdriver/Http4kWebDriverTest.kt
Currently redirect chains to a different host will all have the host header of the domain that triggered the first redirect, not the true host header that would be seen from a browser following the redirects.
=> Support redirects in Http4kWebDriver's emulation of a client's host header

http4k-core/src/main/kotlin/org/http4k/core/ResponseCacheExt.kt, http4k-core/src/test/kotlin/org/http4k/core/ResponseCacheExtTest.kt
A small extension to mark a response as Cache-Control: immutable, useful for revved assets with long cache times.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
=> Add an extension on Response to mark it as Cache-Control: immutable

http4k-aws/src/main/kotlin/org/http4k/aws/AwsCanonicalRequest.kt, http4k-aws/src/test/kotlin/org/http4k/aws/AwsCanonicalRequestTest.kt
Without this, creating a URI such as the one below would lead to an `AwsCanonicalRequest` that doesn't match what Amazon expects.
`Uri.of("http://www.google.com").path("foo")`
whereas this would be valid
`Uri.of("http://www.google.com/foo")`
This fix will ensure both of them would result in the expected `AwsCanonicalRequest`
=> Fix error with AwsCanonicalRequest path normalization

http4k-aws/src/main/kotlin/org/http4k/aws/AwsPreSignRequests.kt, http4k-aws/src/test/kotlin/org/http4k/aws/AwsPreRequestSignerTest.kt, http4k-aws/src/test/kotlin/org/http4k/aws/AwsPreSignRequestsTest.kt
I forgot to support a credentials provider.  Here it is.
I think I know how @daviddenton would have architected this. Rather than have a class with multiple constructors, there would have been an `object AwsPresignRequests` with two `operator fun invoke` functions (or just two top-level `AwsPresignedRequest` functions) that return a `(Request, Duration) -> AwsPresignedRequest`.
It makes no real difference to the user, but if you would prefer I stick to the established http4k style, I don't mind changing it.
=> aws presigner to accept credentials provider

gradle/wrapper/gradle-wrapper.properties, gradlew
tl;dr:
```
BUILD SUCCESSFUL in 5m 27s
622 actionable tasks: 622 executed
```
```
~/git/efasel-http4k$ ./gradlew check
Starting a Gradle Daemon, 2 busy and 2 incompatible Daemons could not be reused, use --status for details
> Task :http4k-template-rocker:compileTestRocker
[main] INFO com.fizzed.rocker.compiler.JavaGeneratorMain - Parsing 3 rocker template files
[main] INFO com.fizzed.rocker.compiler.JavaGeneratorMain - Generated 3 rocker java source files
[main] INFO com.fizzed.rocker.compiler.JavaGeneratorMain - Generated rocker configuration /home/fase01/git/efasel-http4k/http4k-template/rocker/out/test/classes/rocker-compiler.conf
> Task :http4k-contract:generateOpenApi3AutoClient
There were issues with the specification, but validation has been explicitly disabled.
Errors: 
-attribute …
```
=> Upgrade gradle to 8.5

src/docs/guide/reference/htmx/index.md
The current import of the handlebars template engine in the htmx example is not working. (Probably outdated?)
This fixes that tiny bug.
=> Fix handlebars import in htmx example

http4k-client/helidon/src/main/kotlin/org/http4k/client/HelidonClient.kt, http4k-client/helidon/src/test/kotlin/org/http4k/client/HelidonClientTest.kt
The use of Helidon's `uri(String uri)` encodes the string value which breaks the extraction of query parameters.
This change uses the Helidon WebClient API to copy query parameters into a Helidon request.
=> Make HelidonClient support query parameters

http4k-client/apache/src/test/kotlin/org/http4k/client/ApacheClientTest.kt, http4k-client/apache4/src/test/kotlin/org/http4k/client/Apache4ClientTest.kt, http4k-client/fuel/src/main/kotlin/org/http4k/client/Fuel.kt, http4k-client/fuel/src/test/kotlin/org/http4k/client/FuelTest.kt, http4k-client/helidon/src/test/kotlin/org/http4k/client/HelidonClientTest.kt, http4k-client/jetty/src/main/kotlin/org/http4k/client/JettyClient.kt, http4k-client/jetty/src/test/kotlin/org/http4k/client/JettyClientTest.kt, http4k-client/okhttp/src/test/kotlin/org/http4k/client/OkHttpTest.kt, http4k-core/src/test/kotlin/org/http4k/client/Java8HttpClientTest.kt, http4k-core/src/test/kotlin/org/http4k/client/JavaHttpClientTest.kt, http4k-core/src/testFixtures/kotlin/org/http4k/client/HttpClientWithMemoryModeContract.kt, settings.gradle.kts
Requests prepared by `AwsSdkClient` set the body as an input stream which gets consumed when the `PrintRequestAndResponse` filter is combined with specific clients, resulting in the server receiving an empty request body.
The introduction of `HttpClientWithMemoryModeContract` helped identify and fix the impacted clients:
- `http4k-client-fuel`
- `http4k-client-jetty`
=> Make clients honor the memory body mode when a request body is an input stream

http4k-contract/openapi/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3ApiRenderer.kt
I'm using a library called Kondor which provides a way to generate json schemas without the use of reflection etc. In the http4k OpenApi3 implementation, it's currently not possible to provide your own JsonToJsonSchema implementation, however it is in the OpenApi2 implementation.
=> Allow user to provide schema creation implementation

http4k-contract/jsonschema/build.gradle.kts, http4k-contract/jsonschema/src/main/kotlin/org/http4k/contract/jsonschema/v3/KondorJsonSchemaCreator.kt, http4k-contract/openapi/build.gradle.kts, http4k-contract/openapi/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt, http4k-contract/openapi/src/test/kotlin/org/http4k/contract/openapi/v3/OpenApi3KondorTest.kt, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3KondorTest.duplicate schema models are not rendered.approved, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3KondorTest.renders as expected.approved, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3KondorTest.renders json schema bodies that use data classes.approved, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3KondorTest.when enabled renders description including its own path.approved, http4k-format/kondor-json/src/main/kotlin/org/http4k/format/KondorJson.kt
This PR adds a KondorJsonSchemaCreator which can be used to produce well defined schemas via Kondor's inbuilt schema generation capabilities.
=> Implement KondorJsonSchemaCreator

http4k-core/src/main/kotlin/org/http4k/routing/static.kt, http4k-core/src/test/kotlin/org/http4k/routing/StaticPrefixRoutingTest.kt, http4k-core/src/testFixtures/kotlin/org/http4k/routing/StaticRoutingHttpHandlerTest.kt
I had to attempt to load the directory path, and then load it with `/index.html` if that was null - because it's not possible to determine whether a path is a directory or not when doing `javaClass.getResource`.
I have still left `convertPath` adding `/index.html` when it encounters `/` or an empty string. All tests will pass without this, but it seemed to me that the root path will always be `/index.html` so convertPath is doing the right thing. By leaving this in convertPath it means that `load(...)` will be called once with `/index.html` rather than being called twice.
Another approach would have been to make determining whether to add `/index.html` to the path the responsibility of the `ResourceLoader`. The `ResourceLoader.Directory` is able to determine whether the path is a …
=> Static handlers serve an index.html file from a subdirectory

http4k-core/src/main/kotlin/org/http4k/lens/Validator.kt
don't allocate LensFailure (which is an Exception with stacktrace) if there are no errors
=> Validator optimisation

http4k-testing/tracerbullet/src/main/kotlin/org/http4k/tracing/TracerBullet.kt, http4k-testing/tracerbullet/src/test/kotlin/org/http4k/tracing/TracerBulletExtraTest.kt, http4k-testing/tracerbullet/src/test/resources/org/http4k/tracing/TracerBulletExtraTest.traces can be grouped.approved
This PR fixes TracerBullet cross-trace spans sharing by grouping spans by their traceId before building a tree.
See discussion in slack https://kotlinlang.slack.com/archives/C5AL3AKUY/p1711545523381239?thread_ts=1711364711.659419&cid=C5AL3AKUY
=> Group spans by traces

http4k-core/src/main/kotlin/org/http4k/lens/lensSpec.kt
BiDiMultiLensSpec was defining methods which were the same as what it was inheriting from BiDiLensBuilder
=> removes some unnecessary code

http4k-cloudnative/src/main/kotlin/org/http4k/cloudnative/env/Environment.kt, http4k-contract/openapi/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt, http4k-contract/openapi/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v2/OpenApi2Test.renders as expected.approved, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.renders as expected.approved, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3KondorTest.renders as expected.approved, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3ServersDefaultTest.renders as expected.approved, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3Test.renders as expected.approved, http4k-core/src/main/kotlin/org/http4k/lens/Meta.kt, http4k-core/src/main/kotlin/org/http4k/lens/lensSpec.kt, http4k-multipart/src/test/kotlin/org/http4k/format/MultipartExtensionsTest.kt, src/docs/guide/howto/integrate_with_openapi/example.kt, src/docs/guide/howto/integrate_with_openapi/index.md
Hi Folks,
We've added an extra field to `Meta` on a lens to enable values to be stuffed under a `schema` key, and then pulled out to add to the OpenAPI spec. This is specific to things that OpenApi considers to be a parameter.
@ivanmoore @jack-bolles and myself paired on these changes, our time was donated by Ford Digital.
=> Lens metadata enables the augmentation of schemas in OpenApi definition

http4k-contract/jsonschema/src/main/kotlin/org/http4k/contract/jsonschema/v3/AutoJsonToJsonSchema.kt, http4k-contract/jsonschema/src/test/kotlin/org/http4k/contract/jsonschema/v3/AutoJsonToJsonSchemaTest.kt, http4k-contract/jsonschema/src/test/resources/org/http4k/contract/jsonschema/v3/AutoJsonToJsonSchemaTest.can write extra properties to map.approved, http4k-contract/jsonschema/src/test/resources/org/http4k/contract/jsonschema/v3/AutoJsonToJsonSchemaTest.renders schema for custom json mapping.approved, http4k-contract/jsonschema/src/test/resources/org/http4k/contract/jsonschema/v3/AutoJsonToJsonSchemaTest.renders schema for raw map field.approved, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.auto rendering renders as expected.approved
We have a requirement where we wish to append non-standard fields, and override the fields http4k attempts to derive for a given schema.
Changes to `SchemaNode` so that it is backed by a map; rather than a strict set of properties. Addition of the ability to supply an order for known properties, unknown properties appear at the bottom, sub-sorted alphabetically.
@ivanmoore @jack-bolles and myself paired on these changes, our time was donated by Ford Digital.
=> Change to allow for any information from FieldMetadata to appear on the final SchemaNode

http4k-client/okhttp/src/main/kotlin/org/http4k/client/OkHttp.kt
Since I deal with generic port-forwarded IoT devices in the hands of consumers, I'm bound to run into weird corner-cases like this one 🙄 .  Not sure if it's reproducible with other clients.
=> OkHttp to handle NoRouteToHostException

http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt
Fixes the current problem where if an http4k server sets surrogate-key headers on responses that are to be cached in Varnish/Fastly/etc, then when the cache revalidates and gets a NOT_MODIFIED from the ETagSupport filter it drops the surrogate-key header, breaking purging by surrogate-key.
=> Add support for surrogate-key headers in EtagSupport

http4k-contract/jsonschema/src/main/kotlin/org/http4k/contract/jsonschema/v3/AutoJsonToJsonSchema.kt, http4k-contract/jsonschema/src/main/kotlin/org/http4k/contract/jsonschema/v3/MetadataRetrieval.kt, http4k-contract/jsonschema/src/test/kotlin/org/http4k/contract/jsonschema/v3/AutoJsonToJsonSchemaTest.kt, http4k-contract/jsonschema/src/test/kotlin/org/http4k/contract/jsonschema/v3/SimpleLookupTest.kt, http4k-contract/jsonschema/src/test/kotlin/org/http4k/contract/jsonschema/v3/SimpleMetadataLookupTest.kt, http4k-contract/jsonschema/src/test/resources/org/http4k/contract/jsonschema/v3/AutoJsonToJsonSchemaTest.can add extra properties to a root component.approved, http4k-contract/openapi/src/main/kotlin/org/http4k/contract/openapi/v3/jacksonExt.kt, http4k-contract/openapi/src/test/kotlin/org/http4k/contract/openapi/v3/OpenApi3AutoTest.kt, http4k-contract/openapi/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.auto rendering renders as expected.approved
Previously only fields on object could be annotated by metadata, this is a proposal to fix that. It should be 100% backwards compatible.
Our time has been donated by Ford Digital
=> Allow for FieldMetadata to be collected for root Schemas

http4k-format/core/src/main/kotlin/org/http4k/format/AutoMarshalling.kt, http4k-format/jackson-xml/src/main/kotlin/org/http4k/format/ConfgurableJacksonXml.kt, http4k-format/jackson-yaml/src/main/kotlin/org/http4k/format/ConfigurableJacksonYaml.kt, http4k-format/jackson/src/main/kotlin/org/http4k/format/ConfigurableJackson.kt
This allows some implementations to avoid creating an intermediate string when serializing directly to an `InputStream`.
=> Allow overriding of `Automarshalling.asInputStream(Any)`

http4k-format/jackson-csv/src/main/kotlin/org/http4k/format/ConfigurableJacksonCsv.kt, http4k-format/jackson-csv/src/test/kotlin/org/http4k/format/jacksonCsvTests.kt
When `CsvSchema.withHeader` is used, as is for the default schema, then the resulting CSV text should include the header row even if the list of objects to write is empty.
The fix for the issue was simply to close the underlying CSV writer, which causes the headers to be written correctly.
Noticed this issue in one of the projects I'm working on. I replicated the issue using the added test, plus I also added another test to prove the defaultSchema function creates a schema with headers enabled.
Potentially breaking fix I guess.
=> Write CSV header even for empty list

http4k-core/src/main/kotlin/org/http4k/core/Uri.kt, http4k-core/src/test/kotlin/org/http4k/core/UriTest.kt
The `Request` already allows to remove all queries as it has the default parameter value set as "". This adds also the default to `Uri.removeQueries()` so it can remove all queries as well.
---
I'd be happy to provide a test, but I cannot find a direct test for that function to build upon, it seems to be implicitly tested through the test for `Request.removeQueries()`. Where would this new test live?
=> Allows to remove all queries for a URI

http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
We don't emit the CORs headers when no match. See
https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null
=> Fix #1103 - Omit CORs headers if no match,

http4k-core/src/main/kotlin/org/http4k/core/ResponseCacheExt.kt, http4k-core/src/test/kotlin/org/http4k/core/ResponseCacheExtTest.kt
Adds the following functions:
- Update the Cache-Control directives from a Kotlin duration as well as a Java duration
- Add convenience methods for parsing the cache control directives as `Long` values
First contribution to this repo so let me know if I've missed anything and I'll update 😃
=> Add convenience extensions to Response Cache Control methods

src/mkdocs.yml
I thought http4k Lenses were elusive, and then I figured out why. The documentation on Lenses is [published](https://www.http4k.org/guide/concepts/lens/), but it is not actually linked to in the `Concepts` navigation menu:
This PR addresses this issue.
I'm of course happy to fix this PR if there's anything I missed or if you'd like the navigation items reordered, but I tried to put it in a sensible place.
Similarly, I'm happy to bin the PR altogether if it's intentionally not included!
=> Add lenses documentation to concepts navigation

http4k-core/src/main/kotlin/org/http4k/core/body/FormBody.kt, http4k-core/src/test/kotlin/org/http4k/core/FormTest.kt, src/docs/guide/howto/use_html_forms/example_standard.kt
This PR adds a more compact way of adding multiple form fields to a request.
Instead of invoking `form(name: String, value: String)` per form field, a single invocation of `form(vararg formData: Pair<String, String>)` will now suffice. This has the added benefit of only parsing the form body once for all fields, as opposed to once per field.
**Considerations**
1. I've named the parameter `formData`. This aligns with how browsers summarise the collection of inputs, but the [spec](https://url.spec.whatwg.org/#application/x-www-form-urlencoded) is a bit more vague. Should we consider changing this name?
>The application/x-www-form-urlencoded format provides a way to encode a [list](https://infra.spec.whatwg.org/#list) of [tuples](https://infra.spec.whatwg.org/#tuple), each consisting of a …
=> Add `form(vararg formData: Pair<String, String>)` request helper

http4k-core/src/main/kotlin/org/http4k/core/Status.kt
Adding additional HTTP error codes, as I encountered some of them that were not yet supported by http4k.
* [423 Locked](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/423)
* [424 Failed Dependency](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/424)
* [425 Too Early](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/425)
* [428 Precondition Required](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/428)
* [431 Request Header Fields Too Large](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431)
=> Add additional HTTP error codes

http4k-testing/kotest/src/main/kotlin/org/http4k/kotest/cookie.kt, http4k-testing/kotest/src/main/kotlin/org/http4k/kotest/request.kt, http4k-testing/kotest/src/main/kotlin/org/http4k/kotest/response.kt, http4k-testing/kotest/src/test/kotlin/org/http4k/kotest/RequestMatchersTest.kt, http4k-testing/kotest/src/test/kotlin/org/http4k/kotest/ResponseMatchersTest.kt
The functions `haveSetCookie` and `haveCookie` were not handling the situation when the cookie wasn't present in the `Response` or `Request` object, resulting in tests failing when they should be passing. Instead it was throwing a `NullPointerException`.
I have made the Cookie `haveValue` function return a `Matcher` with a nullable Cookie type and removed the non-null assertion in `haveCookie` and `haveSetCookie`.
=> Fix #1139 - fix haveSetCookie and haveCookie to work when cookie isn't present

http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
As mentioned in [this issue](https://github.com/http4k/http4k/issues/306#issuecomment-1640075947).
`Vary` header should include 'Origin' in its list if a specific value is included in the `Access-Control-Allow-Origin` header, so that caches know to include the origin in the cache key. Docs [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#access-control-allow-origin) and [here](https://httpwg.org/specs/rfc9110.html#field.vary).
=> Include Vary header on CORS responses

http4k-multipart/src/main/kotlin/org/http4k/core/MultipartFormBody.kt, http4k-multipart/src/main/kotlin/org/http4k/lens/multipartForm.kt, http4k-multipart/src/main/kotlin/org/http4k/lens/parts.kt, http4k-multipart/src/test/kotlin/org/http4k/lens/MultipartFormTest.kt, http4k-multipart/src/test/kotlin/org/http4k/multipart/LiveServerTest.kt
- Multipart Lenses will now share a single `DiskLocation` for all lens extractions
- Fixed an order-of-operations error while deleting multipart files
- Ensure disk-backed form fields are deleted correctly
=> Share DiskLocation across all Multipart lens extractions

http4k-testing/approval/src/main/kotlin/org/http4k/testing/ApprovalTest.kt, http4k-testing/approval/src/main/kotlin/org/http4k/testing/Approver.kt, http4k-testing/approval/src/test/kotlin/org/http4k/testing/NamedSourceApproverTest.kt
Previously, when there was a mismatch in the Approver, the difference could be seen in the console, but because of the message format and exception type, IDEs like IntelliJ would not be able to offer a diff view (by either clicking on the message in the console or typing Cmd+D when selecting the test in the test runner).
With the changes provided in this PR, that is now possible. For example, if the approved file does not exist, it looks like:
A mismatch looks like:
The change also removes the need for the ApprovalFailed exception class.
It's just a minor change, but one that really makes a difference when using approval test, as one can simply Cmd+D on the failing test method, instead of having to navigate to the actual/approved files in the navigator and running a diff on the files.
=> Better diff messages on Approver missing/mismatch

http4k-resilience4j/build.gradle.kts, http4k-resilience4j/src/main/kotlin/org/http4k/filter/ResilienceFilters.kt, http4k-resilience4j/src/test/kotlin/org/http/filter/ResilienceFiltersTest.kt, versions.properties
Allows using resilience4j timeouts through a simple filter.
Standard usage:
```kotlin
ResilienceFilters.TimeLimit(TimeLimiter.of(Duration.ofMillis(500)))
.then {
val upstreamResponse = callSomeSlowApi()
Response(OK).body(upstreamResponse)
}
```
I don't know if allowing passing in the executor service is overkill, but it allows users a bit more control over what threads are used if they want it. If you'd rather not use that, just remove the second & third commits.
If there's any other reason this functionality wasn't already included or you just don't want it, feel free to close this PR 🙂
=> Add resilience4j timeout filter

http4k-core/src/main/kotlin/org/http4k/core/HttpTransaction.kt, http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/test/kotlin/org/http4k/client/Java8HttpClientTest.kt, http4k-core/src/test/kotlin/org/http4k/core/HttpTransactionTest.kt, http4k-core/src/test/kotlin/org/http4k/events/HttpEventTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt, http4k-testing/chaos/src/test/kotlin/org/http4k/chaos/helper.kt, http4k-testing/hamkrest/src/test/kotlin/org/http4k/hamkrest/HttpTransactionMatchersTest.kt, http4k-testing/kotest/src/test/kotlin/org/http4k/kotest/HttpTransactionMatchersTest.kt, http4k-testing/strikt/src/test/kotlin/org/http4k/strikt/HttpTransactionAssertionsTest.kt
This makes it simpler to report the time of request accurately.
I had to change the Java8HttpClient test to fix a test failure.  Please check that it uses the contract base class as intended.
I added the `start` property as the final constructor parameter to ensure that this change does not break code that deconstructs HttpTransaction values.
=> Add `start` time property to HttpTransaction

http4k-format/gson/src/main/kotlin/org/http4k/format/ConfigurableGson.kt, http4k-format/gson/src/test/kotlin/org/http4k/format/GsonTest.kt, http4k-format/jackson-csv/src/main/kotlin/org/http4k/format/ConfigurableJacksonCsv.kt, http4k-format/jackson-csv/src/test/kotlin/org/http4k/format/jacksonCsvTests.kt, http4k-format/jackson-xml/src/main/kotlin/org/http4k/format/ConfgurableJacksonXml.kt, http4k-format/jackson-xml/src/test/kotlin/org/http4k/format/JacksonXmlTest.kt, http4k-format/jackson-yaml/src/main/kotlin/org/http4k/format/ConfigurableJacksonYaml.kt, http4k-format/jackson-yaml/src/test/kotlin/org/http4k/format/jacksonYamlTests.kt, http4k-format/jackson/src/main/kotlin/org/http4k/format/ConfigurableJackson.kt, http4k-format/jackson/src/test/kotlin/org/http4k/format/jacksonJsonTests.kt, http4k-format/klaxon/src/main/kotlin/org/http4k/format/ConfigurableKlaxon.kt, http4k-format/klaxon/src/test/kotlin/org/http4k/format/klaxonJsonTests.kt, http4k-format/kondor-json/src/main/kotlin/org/http4k/format/KondorJson.kt, http4k-format/kondor-json/src/test/kotlin/org/http4k/format/KondorJsonAutoMarshallingJsonTest.kt, http4k-format/kotlinx-serialization/src/main/kotlin/org/http4k/format/ConfigurableKotlinxSerialization.kt, http4k-format/kotlinx-serialization/src/test/kotlin/org/http4k/format/KotlinxSerializationAutoTest.kt, http4k-format/moshi-yaml/src/main/kotlin/org/http4k/format/ConfigurableMoshiYaml.kt, http4k-format/moshi-yaml/src/test/kotlin/org/http4k/format/moshiYamlTests.kt, http4k-format/moshi/src/main/kotlin/org/http4k/format/ConfigurableMoshi.kt, http4k-format/moshi/src/test/kotlin/org/http4k/format/MoshiTest.kt, http4k-format/xml/src/main/kotlin/org/http4k/format/Xml.kt, http4k-format/xml/src/test/kotlin/org/http4k/format/XmlTest.kt
Currently the `.auto()` that comes with `format` automarshalling is way more powerful than `asA`/`asFormatString` - but is only useable with `HttpMessage`.
Therefore I've added `asBiDiMapping` that will create an instance of bidirectional lens in exactly same way as it is done in `auto()`.
=> Adding ability to create BiDiMapping lens

http4k-core/src/main/kotlin/org/http4k/core/Accept.kt, http4k-core/src/main/kotlin/org/http4k/core/ContentType.kt, http4k-core/src/main/kotlin/org/http4k/lens/header.kt, http4k-core/src/test/kotlin/org/http4k/lens/HeaderTest.kt
Currently, if the `q=` parameter is present, it'll parse the headers incorrectly. 
Moreover, the `directives` property in `Accept` makes no sense as parameters should always be associated with a content type.
=> Fix parsing of Accept headers

CHANGELOG.md, core/realtime-core/src/main/kotlin/org/http4k/routing/internalSse.kt, core/realtime-core/src/main/kotlin/org/http4k/sse/sse.kt, core/realtime-core/src/test/kotlin/org/http4k/sse/SseClientTest.kt, core/realtime-core/src/testFixtures/kotlin/org/http4k/sse/SseServerContract.kt, core/server/helidon/src/main/kotlin/org/http4k/server/HelidonHandler.kt, core/server/jetty/src/main/kotlin/org/http4k/server/JettyEventStreamHandler.kt, core/server/jetty11/src/main/kotlin/org/http4k/server/Jetty11EventStreamHandler.kt, core/server/undertow/src/main/kotlin/org/http4k/server/Http4kUndertowSseFallbackHandler.kt, core/server/undertow/src/main/kotlin/org/http4k/server/Http4kUndertowSseHandler.kt, core/server/undertow/src/main/kotlin/org/http4k/server/Undertow.kt
We want to be able to fallback in order that the HTTP handler has the chance to match the request even if it's an EventStream request (it's just HTTP after all!).
=> Add fallback from SSE to HTTP if event stream request cannot be matched in SSE

core/core/src/main/kotlin/org/http4k/core/ContentType.kt, core/core/src/test/kotlin/org/http4k/core/ContentTypeTest.kt
Named as per the [media type spec](https://www.rfc-editor.org/rfc/rfc6838#section-4.2.8).
Lets you write stuff like 
```kotlin
if (response.contentType()?.structure() == "json") {
// do something
}
```
=> Utility function to get the structure suffix from a content type

core/contract/src/main/kotlin/org/http4k/contract/openapi/v2/OpenApi2.kt, core/contract/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt, core/contract/src/main/kotlin/org/http4k/contract/routeMeta.kt, core/contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt, core/contract/src/test/resources/org/http4k/contract/openapi/v2/OpenApi2Test.renders as expected.approved, core/contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.renders as expected.approved, core/contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3KondorTest.renders as expected.approved, core/contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3ServersDefaultTest.renders as expected.approved, core/contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3Test.renders as expected.approved, core/contract/src/test/resources/org/http4k/contract/simple/SimpleJsonTest.renders as expected.approved
Issue link: https://github.com/http4k/http4k/issues/1221
This change we will also allow to use [openapi-generator](https://github.com/OpenAPITools/openapi-generator) to generate file types e.g. Blob for Typescript.
=> Fix #1221 Lack of ability to automatically generate valid Open API schemas for downloading files

core/core/src/main/kotlin/org/http4k/core/cookie/Cookie.kt, core/core/src/main/kotlin/org/http4k/core/cookie/CookieExtensions.kt, core/core/src/test/kotlin/org/http4k/core/cookie/CookieTest.kt, core/core/src/test/kotlin/org/http4k/filter/ClientCookiesTest.kt
1. When the cookie has no attributes, don't end the string in a trailing `; `. 
- As per [the spec](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.1), specifically the line `set-cookie-string = cookie-pair *( ";" SP cookie-av )`
- I guess there's a chance this may break tests for consumers that are currently asserting the precise cookie string value?
2. Allow the setting of an unquoted cookie on a `Response`
3. Allow the invalidation of a cookie with a path
=> Updates to formatting of cookies

connect/amazon/iamidentitycenter/client/src/main/kotlin/org/http4k/connect/amazon/iamidentitycenter/SSOCacheManager.kt, connect/amazon/iamidentitycenter/client/src/main/kotlin/org/http4k/connect/amazon/iamidentitycenter/pathExtensions.kt
SSO cache files created by aws cli are owner restricted. This pull request ensures that cache files created by http4 have correct permissions.
=> Files containing tokens should only be readable by owner

core/core/src/testFixtures/kotlin/org/http4k/server/ServerContract.kt, core/server/jetty/src/main/kotlin/org/http4k/server/Http4kJettyHttpHandler.kt
Fixes #1255. Do not use headers.getCSV in Jetty server implementation to avoid rewriting of headers Added a new server contract test to validate that this issue is fixed.
=> Fix for #1255. Do not use headers.getCSV in Jetty server implementation to avoid manipulation.

core/core/src/main/kotlin/org/http4k/lens/lens.kt
Allows library users to extend `BiDiLens` for custom implementations of `invoke`, as is currently possible with `Lens`.
Resolves issue #1268.
=> Make BiDiLens open

core/aws/src/main/kotlin/org/http4k/aws/AwsRequestPreSigner.kt, core/aws/src/main/kotlin/org/http4k/aws/requestExtensions.kt, core/aws/src/main/kotlin/org/http4k/filter/awsExtensions.kt
At the moment amazon s3 client cannot handle files that contain '+' character in the file name. Request fails with SignatureDoesNotMatch error. There seem to be a known issue with AWS not handling + sign in request path in a standard way (https://jamesd3142.wordpress.com/2018/02/28/amazon-s3-and-the-plus-symbol/). This issue is also discussed here:  https://github.com/akka/alpakka/issues/838 . The solution is to replace '+' with '%2B' after request has been signed.
=> Fix mismatched request signature error when s3 path contains plus symbol

CHANGELOG.md, core/template/core/src/main/kotlin/org/http4k/template/ViewModel.kt
Fixes #1279
Previously, template paths were calculated using the system file seperator, which is `\` on Windows.  This seperator is not valid on the classpath, so I have hardcoded it to `/`.
I'm concerned about this affecting file-based template loading, but the `TemplatesContract`, which tests file loading, seems to still pass.
=> fix classpath template loading on windows

core/format/moshi/src/main/kotlin/org/http4k/format/ConfigurableMoshi.kt
This change should help in parsing JSON in lenient mode (as stated here in Moshi: [JsonReader.kt](https://github.com/square/moshi/blob/256b13b3bfd6cb5557c857496e674b0b1ab98d10/moshi/src/main/java/com/squareup/moshi/JsonReader.kt#L200-L200)), as per the lenient param in the ConfigurableMoshi constructor.
=> Add `lenient()` for adapter for Lenient strictness in ConfigurableMoshi

connect/google/analytics-core/src/main/kotlin/org/http4k/connect/google/analytics/filter/CollectPageView.kt, connect/google/analytics-ga4/client/src/test/kotlin/org/http4k/connect/google/analytics/ga4/CollectPageViewTest.kt, core/core/src/main/kotlin/org/http4k/core/ProtocolTransaction.kt, core/core/src/main/kotlin/org/http4k/events/HttpEvent.kt, core/core/src/main/kotlin/org/http4k/events/ProtocolEvent.kt, core/core/src/main/kotlin/org/http4k/routing/extensions.kt, core/core/src/main/kotlin/org/http4k/routing/messages.kt, core/core/src/test/kotlin/org/http4k/core/ReportHttpTransactionTest.kt, core/ops/opentelemetry/src/main/kotlin/org/http4k/filter/tracingFiltersOpenTelemetryExtensions.kt, core/realtime-core/src/main/kotlin/org/http4k/events/SseEvent.kt, core/realtime-core/src/main/kotlin/org/http4k/events/WsEvent.kt
This provides a workaround for #1294 . I'm not crazy about it as it makes the xUriTemplate nullable in the `RoutedMessage` and technically it's a break, but it's a start and may be cleaner than just implementing another RoutedRequest/Response wrapper.
=> Make xUriTemplate nullable in RoutedMessage... 

connect/amazon/systemsmanager/client/src/main/kotlin/org/http4k/connect/amazon/systemsmanager/action/GetParameters.kt, connect/amazon/systemsmanager/client/src/testFixtures/kotlin/org/http4k/connect/amazon/systemsmanager/SystemsManagerContract.kt, connect/amazon/systemsmanager/fake/src/main/kotlin/org/http4k/connect/amazon/systemsmanager/FakeSystemsManager.kt, connect/amazon/systemsmanager/fake/src/main/kotlin/org/http4k/connect/amazon/systemsmanager/endpoints.kt
At the moment only getParameter that can retrieve a single Parameter is supported. This pull request adds support for getParameters endpoint that can retrieve multiple parameters at one go. It is also useful for retrieving a parameter that might not exist as it returns collection of parameters and does not throw if requested parameter does not exist.
=> Added support for SystemManager.getParameters endpoint

core/realtime-core/src/testFixtures/kotlin/org/http4k/websocket/WebsocketServerContract.kt, core/server/helidon/src/test/kotlin/org/http4k/websocket/HelidonWebsocketTest.kt
Helidon fails to provide the headers from the upgrade request.  This PR will add the missing coverage, with the exception for Helidon.
=> add coverage for websocket server headers

connect/storage/redis/build.gradle.kts, connect/storage/redis/src/main/kotlin/org/http4k/connect/storage/RedisStorage.kt, connect/storage/redis/src/test/kotlin/org/http4k/connect/storage/RedisStorageTest.kt, core/tools/traffic-capture/build.gradle.kts, core/tools/traffic-capture/src/main/kotlin/org/http4k/traffic/ReadWriteCache.kt, core/tools/traffic-capture/src/test/kotlin/org/http4k/traffic/ReadWriteCacheTest.kt
- Allow passing a custom duration function when constructing a Redis instance, so you can cache an object for a different duration depending on its properties.
- In org.http4k.traffic, add an extension to transform a Storage instance into a ReadWriteCache. http4k-connect-storage-core is included as a compileOnly dependency so you don't automatically ship these two modules together, but if you've got them both you can use this function
These two additions between them mean you can do things like easily use REDIS as a cache in front of an HTTP client, caching the responses for different durations depending on their max-age.
=> Some additions to http4k-connect-storage

connect/amazon/core/src/testFixtures/kotlin/org/http4k/connect/amazon/AwsEnvironment.kt, connect/amazon/s3/client/src/testFixtures/kotlin/org/http4k/connect/amazon/s3/S3BucketContract.kt, connect/amazon/s3/fake/src/main/kotlin/org/http4k/connect/amazon/s3/endpoints/common.kt, connect/amazon/s3/fake/src/main/kotlin/org/http4k/connect/amazon/s3/endpoints/deleteKey.kt, connect/amazon/s3/fake/src/main/kotlin/org/http4k/connect/amazon/s3/endpoints/getKey.kt, connect/amazon/s3/fake/src/main/kotlin/org/http4k/connect/amazon/s3/endpoints/putKey.kt, core/platform/aws/src/main/kotlin/org/http4k/aws/AwsCanonicalRequest.kt, core/platform/aws/src/main/kotlin/org/http4k/aws/AwsRequestPreSigner.kt, core/platform/aws/src/main/kotlin/org/http4k/aws/requestExtensions.kt, core/platform/aws/src/main/kotlin/org/http4k/filter/awsExtensions.kt
Standard AWS s3 client supports s3 bucket keys containing hashes (#). This pull request adds support for bucket keys with hashes in http4k-connect. I have included a contract test for keys with hashes, pluses and spaces. This pull request also fixes an issue, where bucket keys containing spaces were not supported by JavaHttpClient, it only worked with OkHttp.
=> Added support for s3 bucket keys containing hash (#). 

connect/amazon/s3/client/src/testFixtures/kotlin/org/http4k/connect/amazon/s3/S3BucketContract.kt, connect/amazon/s3/fake/src/main/kotlin/org/http4k/connect/amazon/s3/endpoints/common.kt, core/platform/aws/src/main/kotlin/org/http4k/aws/AwsCanonicalRequest.kt, core/platform/aws/src/main/kotlin/org/http4k/aws/AwsRequestPreSigner.kt, core/platform/aws/src/main/kotlin/org/http4k/aws/requestExtensions.kt, core/platform/aws/src/main/kotlin/org/http4k/filter/awsExtensions.kt, core/platform/aws/src/test/kotlin/org/http4k/aws/AwsCanonicalRequestTest.kt, core/platform/aws/src/test/kotlin/org/http4k/aws/RequestExtensionsTest.kt
Fixes issues with keys containing '%', allows for '/' after '#',  added more special characters to the test. Changed the order of Url encoding for AWS requests. The path encoding logic moved out of AwsCanonicalRequest. Url is now encoded in the full request before canonical request is created, and the same path encoding logic that is used for signing now also applies to http client. Hopefully this fixes all encoding and AWS signature mismatch issues once and for all.
=> More fixes for special characters in s3 bucket key

connect/amazon/sqs/client/src/main/kotlin/org/http4k/connect/amazon/sqs/action/SendMessage.kt
An InvalidParameterException occurs due to the invalid SQS SendMessage request DTO field name 'MessageDeDuplicationId' when we try to send a message to a queue without ContentBasedDeduplication feature.
=> Correct SQS SendMessage request DTO

core/client/helidon/src/main/kotlin/org/http4k/client/HelidonClient.kt, core/client/helidon/src/test/kotlin/org/http4k/client/HelidonClientTest.kt
Similar to the [Jetty implementation](https://github.com/ollieabbey/http4k/blob/249ad0c727f5f1cabae0b4d2c22af999a532722a/core/client/jetty/src/main/kotlin/org/http4k/client/JettyClient.kt#L40).
Possible solution to https://github.com/http4k/http4k/issues/1339
=> Allow modification of Helidon requests

core/testing/webdriver/src/main/kotlin/org/http4k/webdriver/Http4kWebDriver.kt, core/testing/webdriver/src/test/kotlin/org/http4k/webdriver/RedirectTest.kt
refreshing the page should, if the response is a redirect, update the uri and the body of the current page.
=> redirect on refresh

core/api/graphql/src/main/kotlin/org/http4k/graphql/model.kt, core/api/graphql/src/test/kotlin/org/http4k/client/GraphQLClientTest.kt, core/api/graphql/src/test/kotlin/org/http4k/graphql/GraphQLResponseTest.kt, core/api/graphql/src/test/kotlin/org/http4k/routing/GraphQLRoutingTest.kt
The [spec](https://spec.graphql.org/October2021/#sec-Response-Format) says: The response map may also contain an entry with key extensions. This entry, if set, must have a map as its value.
This PR will copy the extensions from the ExecutionResult into the GraphQLResponse.
For instance the [Apollo-tracing](https://github.com/apollographql/apollo-tracing?tab=readme-ov-file) compatible [TracingInstrumentation class from graphql-java](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java) uses this field, which can then be displayed by the already included graphql-playground UI.
=> Add support for root-level GraphQL extensions field in GraphQLResponse

core/ops/opentelemetry/src/main/kotlin/org/http4k/filter/tracingFiltersOpenTelemetryExtensions.kt
When using otel collector with awsxray exporter, http status code is exported as 0, even though OpenTelemetryTracing filter sets "http.status_code" attribute that should be recognised by the collector. The issue seems to be with the type of the attribute. OpenTelemetryTracing sets this attribute as String, but collector expects it to be Long. 
The "http.status_code" attribute has been deprecated in favour of io.opentelemetry.semconv.HttpAttributes.HTTP_RESPONSE_STATUS_CODE = [http.response.status_code](https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/) , which is also of type Long. However both Attributes are recognised as long as the value is of type Long. I have not changed to the new attribute name to make this pull request less likely to break existing …
=> Open Telemetry integration, http status is not recognised. Use correct type Long for http.status_code attribute. 

CHANGELOG.md
Not sure why it was removed in the first place.
=> Add new CloudWatch module to changelog once more

core/core/src/main/kotlin/org/http4k/routing/spa.kt, core/core/src/test/kotlin/org/http4k/routing/SinglePageAppRoutingHttpHandlerTest.kt
Currently, it ignores the mounted path, allowing serving content to incorrect paths.
Fix #1376
=> Fix SPA routing when it's mounted to a non-root path

connect/amazon/ses/client/src/main/kotlin/org/http4k/connect/amazon/ses/model/EmailContent.kt
=> Add support for base64 encoded AWS SESv2 attachments

core/core/src/main/kotlin/org/http4k/lens/ParamMeta.kt, core/core/src/main/kotlin/org/http4k/lens/contentNegotiationHeaders.kt, core/core/src/main/kotlin/org/http4k/routing/negotiation.kt, core/core/src/test/kotlin/org/http4k/routing/StandardAcceptHeadersRoutingTest.kt
Also removes routing by negotiated content encoding.  This will be better implemented as a filter, and I don't want to add an unnecessary feature to the public API.
=> Better error messages from content negotiation

core/core/src/test/kotlin/org/http4k/routing/StandardAcceptHeadersRoutingTest.kt
My last PR left some unused imports in the test class
=> Tidy: Remove unused imports

core/template/htmlflow/build.gradle.kts, core/template/htmlflow/src/main/kotlin/org/http4k/template/HtmlFlowExtensions.kt, core/template/htmlflow/src/main/kotlin/org/http4k/template/HtmlFlowTemplates.kt, core/template/htmlflow/src/test/kotlin/AtRootBob.kt, core/template/htmlflow/src/test/kotlin/org/http4k/template/HtmlFlowTemplatesTest.kt, core/template/htmlflow/src/test/kotlin/org/http4k/template/contract/HtmlFlowTemplatesContract.kt, core/template/htmlflow/src/test/kotlin/org/http4k/template/contract/HtmlFlowViewModelContract.kt, core/template/htmlflow/src/test/kotlin/org/http4k/template/onClassPathNotAtRoot.kt, core/template/htmlflow/src/test/kotlin/org/http4k/template/onClasspath.kt, gradle/libs.versions.toml
Adds HtmlFlow Templates support, as discussed [here](https://github.com/xmlet/HtmlFlow/issues/122#issuecomment-3185468741)
Supported methods:
- `CachingClasspath`: Scans package paths for `HtmlView` definitions with view caching
- `HotReloadClasspath`: Same scanning with hot reload capability  
- `Caching`: Converts directory paths to package paths for classpath-based scanning
- `HotReload`: Same as `Caching` with hot reload enabled
- `HtmlView<T>.renderer()`: Creates a `TemplateRenderer` directly from an `HtmlView`
=> Add support for HtmlFlow templates
