http4k/http4k

http4k-template-dust/src/main/kotlin/org/http4k/template/DustTemplates.kt, http4k-template-dust/src/main/kotlin/org/http4k/template/dust/Dust.kt, http4k-template-dust/src/test/kotlin/org/http4k/template/DustTemplatesTest.kt, http4k-template-dust/src/test/resources/org/http4k/template/NeedsHelpers.dust, http4k-template-dust/src/test/resources/org/http4k/template/dust-helpers.js
Apps can pass a list of scripts to run after Dust is initialised, to register helpers.
=> Can add helpers to the Dust template engine.

http4k-core/src/main/kotlin/org/http4k/filter/ClientFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
…d -> parentSpanId and creates a new spanId, on outgoing requests
=> Fixes #74 - correcting parentSpanId and spanId for request tracing

http4k-core/src/main/kotlin/org/http4k/lens/lensSpec.kt
This PR makes it easier to choose a custom date/time formatter when creating a lens.
=> Lens date time formatting

.travis.yml, release-site.sh
Not sure if `TRAVIS_PULL_REQUEST` is exported to the subshell - in any case, this is how Travis themselves recommend accomplishing this.
Here goes nothing...
=> Changed doc invocation via YML to avoid PR builds

http4k-core/src/main/kotlin/org/http4k/core/Parameters.kt, http4k-core/src/main/kotlin/org/http4k/core/body/FormBody.kt, http4k-core/src/test/kotlin/org/http4k/core/ParametersTest.kt
https://github.com/http4k/http4k/issues/143
=> Conversions between Parameters and map

http4k-incubator/src/main/kotlin/org/http4k/routing/experimental/InMemoryResource.kt, http4k-incubator/src/main/kotlin/org/http4k/routing/experimental/ResourceListingHandler.kt
Blimey, I contribute the stuff and then you take it away from me!
InMemoryResource is a convenience by anyone wanting to implement their own resource serving.
ResourceListingHandler is needed if you want to implement your own listings (I do!)
=> Make some useful things public

http4k-jsonrpc/src/main/kotlin/org/http4k/jsonrpc/JsonRpcService.kt, http4k-jsonrpc/src/main/kotlin/org/http4k/jsonrpc/jsonRpc.kt, http4k-jsonrpc/src/test/kotlin/org/http4k/jsonrpc/JsonRpcServiceTests.kt
Some code cleanup to please Codebeat.
Also ensure the "manual" test actually used the manual mapper.
=> JSON-RPC module - cleanup of code

http4k-testing-webdriver/src/main/kotlin/org/http4k/webdriver/JSoupWebElement.kt, http4k-testing-webdriver/src/test/kotlin/org/http4k/webdriver/Http4kWebDriverTest.kt, http4k-testing-webdriver/src/test/kotlin/org/http4k/webdriver/JSoupWebElementTest.kt, http4k-testing-webdriver/src/test/resources/test.html
- detect buttons if they are clicked on
- avoid losing host name/protocol/authority for form submissions
- check a couple of different way actions can be specified
- add negative equality test on elements since we rely on that in the form code
=> improve web driver support for forms

http4k-aws/src/main/kotlin/org/http4k/aws/AwsCredentials.kt, http4k-aws/src/main/kotlin/org/http4k/filter/awsExtensions.kt, http4k-aws/src/test/kotlin/org/http4k/aws/AwsAuthClientFilterTest.kt
Added optional sessionToken to AwsCredentials and include it in the signed request if present
=> Include session token in AwsCredentials

http4k-core/src/main/kotlin/org/http4k/lens/RequestContextKey.kt
=> Replace RequestContexts with reference to Store<RequestContext> interface

http4k-core/src/main/kotlin/org/http4k/routing/routing.kt, http4k-core/src/test/kotlin/org/http4k/routing/RoutingTest.kt
Removed the double negative from the error message.
=> Updated error message for when a request has not been routed

http4k-format-jackson/src/main/kotlin/org/http4k/format/ConfigurableJackson.kt, http4k-format-jackson/src/test/kotlin/org/http4k/format/JacksonTest.kt
=> Added parameter TypeReference to Jackson writer in ConfigurableJackson.autoBody 

http4k-core/src/main/kotlin/org/http4k/filter/ext.kt, http4k-core/src/test/kotlin/org/http4k/filter/GzipBodyTest.kt
There is a bug in the GZippingInput stream where we will lose data in cases where the pending deflated data exceeds the size of the read buffer. The key cases to replicate appear to be a sufficient set of data to encode, and the shape of the data to be varied enough that the deflater retains it over multiple `read` cycles.
The solution is to check if the deflater has pending data at the start of a read, and ensure its flushed if present. Given the need to retain the deflation buffer we also get to avoid multiple allocations, which should be a very (very) small perf improvement.
This resolves #344.
=> Fixed data-loss issue with GzippingInputStream

buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, http4k-client-websocket/build.gradle
Issue #360 
Not sure whether `implementation` wouldn't be better here.
=> Fix no-op slf4j in http4k-client-websocket

http4k-core/src/main/kotlin/org/http4k/lens/BiDiMapping.kt, http4k-core/src/main/kotlin/org/http4k/lens/path.kt, http4k-core/src/main/kotlin/org/http4k/lens/query.kt, http4k-core/src/test/kotlin/org/http4k/lens/BiDiLensSpecTest.kt, http4k-core/src/test/kotlin/org/http4k/lens/PathTest.kt, http4k-core/src/test/kotlin/org/http4k/lens/QueryTest.kt
Hello,
with this PR I try to introduce way to extract/inject enum instances from/to Query and Path.
I have few questions which I will post as comments on the code.
=> Add enum StringBiDiMapping

http4k-client-websocket/src/main/kotlin/org/http4k/client/WebsocketClient.kt, http4k-client-websocket/src/test/kotlin/org/http4k/client/WebsocketClientTest.kt
=> added auto-reconnection support on blocking WsClient 

http4k-server-netty/src/main/kotlin/org/http4k/server/Netty.kt
I'm unsure of what this line does, but it's just been replaced by `addListener(CLOSE)`. This currently implements response streaming but not request streaming, as request streaming likely requires a complete rewrite.
```
if (request.decoderResult() == SUCCESS) addListener(CLOSE) else ctx.close()	
```
=> Add response streaming to Netty server

http4k-security-oauth/src/main/kotlin/org/http4k/security/oauthProviders.kt, http4k-security-oauth/src/test/kotlin/org/http4k/security/OAuthProvidersTest.kt
I wanted to add also an iCloud provider but that seems to be not that easy :/
=> Add Facebook OAuth provider

buildSrc/src/main/kotlin/Versions.kt, http4k-core/src/main/kotlin/org/http4k/core/http.kt, http4k-core/src/main/kotlin/org/http4k/servlet/Http4kServletAdapter.kt, http4k-core/src/test/kotlin/org/http4k/core/RequestTest.kt, http4k-server-apache/src/main/kotlin/org/http4k/server/ApacheServer.kt, http4k-server-jetty/src/main/kotlin/org/http4k/server/Http4kWebSocketListener.kt, http4k-server-ktorcio/src/main/kotlin/org/http4k/server/KtorCIO.kt, http4k-server-ktornetty/src/main/kotlin/org/http4k/server/KtorNetty.kt, http4k-server-netty/src/main/kotlin/org/http4k/server/Netty.kt, http4k-server-ratpack/src/main/kotlin/org/http4k/server/Ratpack.kt, http4k-server-undertow/src/main/kotlin/org/http4k/server/Undertow.kt
=> Revert "Implementation of remote address and port in Request interface"

http4k-serverless-lambda/integration-test/README.md, http4k-serverless-lambda/integration-test/build.gradle, http4k-serverless-lambda/integration-test/src/test/kotlin/org/http4k/serverless/lambda/DeployServerAsLambdaForClientContract.kt, http4k-serverless-lambda/integration-test/src/test/kotlin/org/http4k/serverless/lambda/client/AwsLambdaApiClient.kt, http4k-serverless-lambda/integration-test/test-function/build.gradle, http4k-serverless-lambda/integration-test/test-function/src/main/kotlin/org/http4k/serverless/lambda/TestFunction.kt, http4k-serverless-lambda/src/main/kotlin/org/http4k/serverless/LambdaFunction.kt
+ improve instructions for running integration tests
=> Allow creating AWS lambda functions using extension rather than reflection

http4k-core/src/main/kotlin/org/http4k/filter/ClientFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt
Extracted BasicAuth to CustomBasicAuth to allow custom header name. Added ProxyBasicAuth.
=> CustomBasicAuth and ProxyBasicAuth

http4k-core/src/main/kotlin/org/http4k/filter/OriginPolicy.kt, http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
Closes gh-487
The discussion regarding this implementation in #488
=> Implemented OriginPolicy for CORS

http4k-core/src/main/kotlin/org/http4k/routing/Router.kt, http4k-core/src/test/kotlin/org/http4k/routing/RoutingTest.kt
=> Fix routing when method is not allowed and path is also invalid

CHANGELOG.md, http4k-security-oauth/src/main/kotlin/org/http4k/security/InsecureCookieBasedOAuthPersistence.kt, http4k-security-oauth/src/main/kotlin/org/http4k/security/OAuthCallback.kt, http4k-security-oauth/src/main/kotlin/org/http4k/security/OAuthPersistence.kt, http4k-security-oauth/src/test/kotlin/org/http4k/security/FakeOAuthPersistence.kt, src/docs/cookbook/custom_oauth_provider/example.kt
=> Expose OIDC id token to OAuthPersistence#assignToken

http4k-core/src/main/kotlin/org/http4k/core/Status.kt, http4k-core/src/test/kotlin/org/http4k/core/StatusTest.kt
This PR fixes the following issue: https://github.com/http4k/http4k/issues/544
=> Bugfix: add nullsafety and fallback for description within the Status

http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt
I couldn't find an eTag handler in the default code. So this is a port of what we're using internally.
* Takes the etag from the response
* If absent, generates a strong etag by hashing the response when we have the response in memory (i.e. it's not streaming)
* Checks this against `if-none-match`, if present, and returns a 304 if appropriate
* Otherwise attaches the etag to the response
=> Add a basic etag filter

http4k-core/src/main/kotlin/org/http4k/lens/lensSpec.kt
The proposal is hopefully self-explanatory :-)
=> Fix disappearing description in BiDiLensSpec.multi.defaulted

http4k-core/src/main/kotlin/org/http4k/filter/FlashAttributesFilter.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
- so that is possible to pass a String after a redirect but only once. It's based on a Request Cookie.
=> FlashAttributesFilter.kt is a Filter that allow Flash Attributes

http4k-realtime-core/src/test/kotlin/org/http4k/websocket/WebsocketServerContract.kt, http4k-server/jetty/src/main/kotlin/org/http4k/server/Http4kWebSocketFrameHandler.kt
This fixes a regression in 3.285.0. Since then the first frame of a multi-frame websocket message was handled as if it were the final frame when using Jetty.
I discovered this when finally getting around to upgrading from 3.284.0 to 4.8.0.0, somewhat unbelievably! 🤯
=> Multi-frame websocket messages are handled in Jetty

http4k-security/digest/src/main/kotlin/org/http4k/filter/clientFilterExtensions.kt, http4k-security/digest/src/main/kotlin/org/http4k/security/digest/DigestAuthProvider.kt, http4k-security/digest/src/main/kotlin/org/http4k/security/digest/DigestAuthReceiver.kt, http4k-security/digest/src/main/kotlin/org/http4k/security/digest/DigestCredential.kt, http4k-security/digest/src/main/kotlin/org/http4k/security/digest/ParameterizedHeader.kt, http4k-security/digest/src/test/kotlin/org/http4k/filter/DigestAuthTest.kt, http4k-security/digest/src/test/kotlin/org/http4k/security/digest/DigestEncoderTest.kt
Improve test coverage for #629
=> Improve digest auth coverage

http4k-opentelemetry/src/main/kotlin/org/http4k/filter/tracingFiltersOpenTelemetryExtensions.kt, http4k-opentelemetry/src/test/kotlin/org/http4k/filter/OpenTelemetryTracingTest.kt
This PR adds the ability to specify mutation functions for the OpenTelemetry spans during creation and pre-completion.
Why, you ask, would you indulge in such madness?
For creation, one use case is added an attribute that contributes to the `Sampler` - this appears to be invokved at `startSpan`, so all information must be available on the span at this stage. For example, we have a case where we wish to allow sampling to be toggled via a user-provided header, and hence we need to set a Span attribute based on the presence/value of that header.
For pre-completion, the general use case would be adding more contextual attributes that you wish to be sent to the tracing server, e.g. was the response cached?
=> Adds ability to mutate OpenTelemetry spans

http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/AutoJsonToJsonSchema.kt, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for custom json mapping.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for holder with generic list.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for list of enums.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for nested arbitrary objects.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for raw map field.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for recursive objects.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for top level generic list.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for top level list.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.renders as expected.approved, http4k-core/src/main/kotlin/org/http4k/routing/inspect/inspection.kt, http4k-core/src/test/kotlin/org/http4k/server/ServerContract.kt, http4k-core/src/test/resources/org/http4k/routing/inspect/RoutePrintingTest.describe matching.approved, http4k-core/src/test/resources/org/http4k/routing/inspect/RoutePrintingTest.describe routes.approved
trim() in Approver was added due to default empty newline at EOF on Linux
=> feat(openApi3): remove oneOf when not needed

src/docs/guide/howto/create_a_custom_json_marshaller/index.md
Slightly expanded explanation of custom marshaller registration
=> Docs custom json marshaller

http4k-core/src/main/kotlin/org/http4k/routing/static.kt, http4k-core/src/test/kotlin/org/http4k/routing/StaticRoutingHttpHandlerTest.kt
=> Fix path conversion for static routing handlers with trailing '/'.

http4k-testing/strikt/src/main/kotlin/org/http4k/strikt/uri.kt, http4k-testing/strikt/src/test/kotlin/org/http4k/strikt/UriAssertionsTest.kt
=> Fix Strikt assertion builder for Uri.path

http4k-core/src/main/kotlin/org/http4k/lens/BiDiMapping.kt, http4k-core/src/main/kotlin/org/http4k/lens/header.kt, http4k-core/src/main/kotlin/org/http4k/lens/path.kt, http4k-core/src/main/kotlin/org/http4k/lens/query.kt, http4k-core/src/test/kotlin/org/http4k/lens/HeaderTest.kt, http4k-core/src/test/kotlin/org/http4k/lens/PathTest.kt, http4k-core/src/test/kotlin/org/http4k/lens/QueryTest.kt
=> add case-insensitive enum lenses for path, query, and header

http4k-core/src/main/kotlin/org/http4k/lens/BiDiMapping.kt, http4k-core/src/main/kotlin/org/http4k/lens/lensSpec.kt, http4k-core/src/test/kotlin/org/http4k/lens/BiDiLensSpecTest.kt, http4k-format/core/src/main/kotlin/org/http4k/format/AutoMappingConfiguration.kt, http4k-format/core/src/test/kotlin/org/http4k/format/AutoMarshallingContract.kt, http4k-format/core/src/test/kotlin/org/http4k/format/AutoMarshallingJsonContract.kt, http4k-format/jackson-yaml/src/test/kotlin/org/http4k/format/jacksonYamlTests.kt, http4k-format/klaxon/src/test/kotlin/org/http4k/format/klaxonJsonTests.kt, http4k-format/kotlinx-serialization/src/test/kotlin/org/http4k/format/KotlinxSerializationAutoTest.kt, http4k-format/moshi-yaml/src/test/kotlin/org/http4k/format/moshiYamlTests.kt
=> Add zoneId, zoneOffset, and locale as default mappings

http4k-graphql/src/main/kotlin/org/http4k/routing/graphQLExtensions.kt
This PR adds a static graphql playground on a configurable route function.
See: https://github.com/http4k/http4k/issues/753
=> GraphQL playground

src/docs/guide/howto/simple_routing/example.kt
Small update fixing example routing for Rita.
=> docs: fix routing for rita

http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
=> add cors exposed headers property

README.md, http4k-contract/src/main/kotlin/org/http4k/contract/ui/SwaggerUi.kt, http4k-contract/src/main/resources/org/http4k/contract/ui/public/index.html, http4k-contract/src/test/kotlin/org/http4k/contract/ui/SwaggerUiTest.kt, http4k-contract/src/test/resources/org/http4k/contract/ui/SwaggerUiTest.can serve swagger ui.approved, src/docs/guide/howto/create_a_swagger_ui/example.kt, src/docs/guide/howto/create_a_swagger_ui/index.md, src/mkdocs.yml
Helper to render a Swagger UI for your OpenApi description; served from CDN for a light footprint.
=> Swagger UI

src/docs/guide/howto/create_a_swagger_ui/index.md, src/docs/guide/howto/use_auto_content_negotiation/index.md
Fixes some markdown issues that weren't obvious in the editor
=> documentation fixes

http4k-client/websocket/src/main/kotlin/org/http4k/client/internal/internal.kt, http4k-client/websocket/src/test/kotlin/org/http4k/client/WebsocketClientTest.kt
=> Nonblocking websocket client to receive binary messages

src/docs/blog/nanoservices/static_file_server.kt, src/docs/guide/howto/configure_an_oauth_server/example.kt, src/docs/guide/howto/monitor_http4k/example_micrometer.kt, src/docs/guide/howto/record_and_replay_http_traffic/example_cache.kt, src/docs/guide/howto/record_and_replay_http_traffic/example_stream.kt, src/docs/guide/howto/structure_your_logs_with_events/example.kt, src/docs/guide/howto/test_using_service_virtualisation/example_junit_contract_tests.kt, src/docs/guide/howto/use_a_custom_oauth_provider/example.kt, src/docs/guide/howto/use_a_templating_engine/example.kt, src/docs/guide/howto/use_html_forms/example_lens.kt, src/docs/guide/reference/clients/TestingWebsockets.kt
This is definetly the last one, _I promise_. see #790
=> align code comments to fit 95 chars per line

http4k-cloudevents/src/test/kotlin/io/cloudevents/http4k/CSVFormat.kt, http4k-contract/build.gradle, http4k-core/src/main/kotlin/org/http4k/KotlinExtensions.kt, http4k-core/src/main/kotlin/org/http4k/core/Parameters.kt, http4k-core/src/main/kotlin/org/http4k/core/Uri.kt, http4k-core/src/main/kotlin/org/http4k/core/http.kt, http4k-core/src/main/kotlin/org/http4k/filter/RequestFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/main/kotlin/org/http4k/traffic/internal.kt, http4k-realtime-core/src/main/kotlin/org/http4k/sse/sse.kt, http4k-serverless/lambda/integration-test/src/test/kotlin/org/http4k/serverless/lambda/testing/setup/aws/lambda/CreateFunction.kt, http4k-serverless/lambda/src/main/kotlin/org/http4k/format/DynamodbEventAdapter.kt, http4k-serverless/lambda/src/main/kotlin/org/http4k/format/KinesisEventAdapter.kt, http4k-serverless/lambda/src/main/kotlin/org/http4k/format/KinesisFirehoseEventAdapter.kt, http4k-serverless/lambda/src/main/kotlin/org/http4k/format/SQSEventAdapter.kt, http4k-serverless/lambda/src/main/kotlin/org/http4k/serverless/utils.kt, http4k-serverless/lambda/src/test/kotlin/org/http4k/format/AwsLambdaMoshiTest.kt, http4k-serverless/lambda/src/test/kotlin/org/http4k/serverless/ApiGatewayRestAwsHttpAdapterTest.kt, http4k-serverless/lambda/src/test/kotlin/org/http4k/serverless/ApiGatewayV1AwsHttpAdapterTest.kt, http4k-serverless/lambda/src/test/kotlin/org/http4k/serverless/ApiGatewayV2AwsHttpAdapterTest.kt, http4k-serverless/lambda/src/test/kotlin/org/http4k/serverless/ApplicationLoadBalancerHttpAdapterTest.kt, http4k-serverless/openwhisk/integration-test/src/test/kotlin/org/http4k/serverless/DeployAction.kt, http4k-serverless/openwhisk/src/main/kotlin/org/http4k/serverless/OpenWhiskFunction.kt, http4k-testing/servirtium/src/main/kotlin/org/http4k/servirtium/GitHub.kt, http4k-testing/servirtium/src/main/kotlin/org/http4k/traffic/extensions.kt, versions.properties
Feel free to cherry pick if you don't want it all.
=> Misc enhancements

http4k-contract/src/main/kotlin/org/http4k/contract/openapi/v3/AutoJsonToJsonSchema.kt, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.can override definition id for a map.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.can override definition id for a raw map.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for map field.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for non-string-keyed map field.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/AutoJsonToJsonSchemaTest.renders schema for raw map field.approved, http4k-contract/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoTest.auto rendering renders as expected.approved
:wave: Hi Folks, not sure if this is a breaking change or not, but I think this should be the default :)
=> Map properties should be nullable by default fixes #842

http4k-realtime-core/src/test/kotlin/org/http4k/websocket/NonBlockingWebsocketClientContract.kt
I can't reproduce the error on my machine, but I think this tweak might help
=> attempt to deflake WebsocketClientNonBlockingTest

src/docs/guide/reference/index.md, src/docs/theme/404.html, src/mkdocs.yml
fixed some broken links and added some missing modules to modules list
=> Fix documentation

src/docs/guide/tutorials/your_first_http4k_app/index.md
Just a small change on the path to the tests in the Tutorials > Your first http4k app :D
=> Update the path for the `HelloWorldClient` in the `index.md`

CHANGELOG.md, http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoute.kt, http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt, http4k-jsonrpc/src/main/kotlin/org/http4k/jsonrpc/JsonRpcService.kt
Resolves https://github.com/http4k/http4k/issues/912
=> Pass request to failResponseFn in ServerFilters.CatchLensFailure

http4k-core/src/main/kotlin/org/http4k/core/Status.kt, src/test/kotlin/settings/WriteLiveTemplates.kt
https://en.wikipedia.org/wiki/HTTP_451
I added it to the LiveTemplates as that seemed like the right thing to do, but not anywhere else
=> adds the (proposed) 451 status code "Unavailable For Legal Reasons"

http4k-core/src/main/kotlin/org/http4k/filter/ClientFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-incubator/src/main/kotlin/org/http4k/tracing/EventNode.kt, http4k-incubator/src/main/kotlin/org/http4k/tracing/Tracer.kt, http4k-incubator/src/main/kotlin/org/http4k/tracing/TracerBullet.kt, http4k-incubator/src/main/kotlin/org/http4k/tracing/tracer/HttpTracer.kt, http4k-incubator/src/main/kotlin/org/http4k/tracing/tracer/TreeWalkerTracer.kt, http4k-incubator/src/test/kotlin/org/http4k/tracing/MyCustomTracer.kt, http4k-incubator/src/test/kotlin/org/http4k/tracing/TracerBulletExtraTest.kt, http4k-incubator/src/test/kotlin/org/http4k/tracing/TracerBulletTest.kt, http4k-incubator/src/test/kotlin/org/http4k/tracing/junit/TracerBulletEventsTest.kt, http4k-incubator/src/test/resources/org/http4k/tracing/TracerBulletExtraTest.traces can be grouped.approved
changes to API to support simpler tracing tree creation
=> Reworking tracing infrastructure

http4k-contract/src/main/kotlin/org/http4k/contract/ContractRoutingHttpHandler.kt, http4k-contract/src/main/kotlin/org/http4k/contract/routeMeta.kt, http4k-contract/src/test/kotlin/org/http4k/contract/ContractRendererContract.kt
=> add option to mark contract routes as not described

src/docs/guide/reference/aws/index.md
In the original version, the enumerated list wasn't rendered correctly (see discussion on [slack](https://kotlinlang.slack.com/archives/C5AL3AKUY/p1688642812413349)).
I propose to name the features this module provides after stating that there are two of them for better readability.
=> Reword module description

http4k-core/src/main/kotlin/org/http4k/filter/ServerFilters.kt, http4k-core/src/main/kotlin/org/http4k/filter/ZipkinTraces.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
also add `@nested` for more of the previously existing tests.
=> new filter to validate zipkin headers

src/docs/guide/tutorials/going_native_with_graal_on_aws_lambda/HelloServerlessHttp4k.kt, src/docs/guide/tutorials/serverless_http4k_with_aws_lambda/HelloServerlessHttp4k.kt, src/docs/guide/tutorials/serverless_http4k_with_aws_lambda/index.ts
https://kotlinlang.slack.com/archives/C5AL3AKUY/p1697746080471189
=> Use V2 Payload for Lambda Examples

http4k-core/src/main/kotlin/org/http4k/filter/ResponseFilters.kt, http4k-core/src/test/kotlin/org/http4k/filter/ResponseFiltersTest.kt
Fixes http4k/http4k#1022
```
BUILD SUCCESSFUL in 3m 23s
622 actionable tasks: 371 executed, 251 up-to-date
```
=> Add etag to response if matching if-none-match request

http4k-testing/webdriver/src/main/kotlin/org/http4k/webdriver/Http4kWebDriver.kt
Enable Http4kWebDriver to work on Windows which was failing due to underlying Windows file system classes being used to handle the path being generated.
Raised in the following issue: [https://github.com/http4k/http4k/issues/1050](https://github.com/http4k/http4k/issues/1050)
=> Replace use of Paths in Http4kWebDriver with non OS specific logic to normalize the path

http4k-format/kondor-json/src/main/kotlin/org/http4k/format/KondorJson.kt
This makes it possible to use KondorJson to lookup converters for arbitrary types. This enables the possibility to generate Json Schemas for user defined classes.
=> Expose KondorJson converterFor method

http4k-testing/webdriver/src/main/kotlin/org/http4k/webdriver/JSoupWebElement.kt, http4k-testing/webdriver/src/test/kotlin/org/http4k/webdriver/Http4kWebDriverTest.kt, http4k-testing/webdriver/src/test/resources/test.html
Basically if the input was inactive, but of type submit, the value would still be sent in the form data
Also fixed it so we can click on submit inputs to submit the form.
=> Webdriver - Bug when submitting with inputs of type submit

http4k-testing/webdriver/src/main/kotlin/org/http4k/webdriver/JSoupWebElement.kt, http4k-testing/webdriver/src/test/kotlin/org/http4k/webdriver/Http4kWebDriverFormTest.kt, http4k-testing/webdriver/src/test/resources/form_element_association.html, http4k-testing/webdriver/src/test/resources/test.html
Hello, it's other Dave again.
Form elements that are not nested in a `form` but are associated with a form through the `form` attribute should be submitted with the form. They should also cause the form to be submitted.
https://html.spec.whatwg.org/#association-of-controls-and-forms
=> Form elements associated with `form` attribute are submitted and can trigger a submit.

http4k-multipart/src/main/kotlin/org/http4k/lens/multipartForm.kt, http4k-multipart/src/test/kotlin/org/http4k/lens/MultipartFormTest.kt
Don't mind the `wip` commit.  I had some failing tests, but after checking out `master`, they're just platform-specific failures 🙄 .
Closes #1142
=> Close backing DiskLocation when MultipartForm closed

http4k-realtime-core/src/main/kotlin/org/http4k/testing/TestWebsocketFactory.kt, http4k-realtime-core/src/main/kotlin/org/http4k/websocket/WebsocketFactory.kt, http4k-realtime-core/src/test/kotlin/org/http4k/testing/TestWebsocketFactoryTest.kt
This MIGHT be good enough to do without a symmetric `WsHandler`.  Now, all you need to do is inject a `WebsocketFactory` into your application, which can be implemented by a real factory, or this fake.
=> Add test version of WebsocketFactory

http4k-testing/webdriver/src/main/kotlin/org/http4k/webdriver/JSoupWebElement.kt, http4k-testing/webdriver/src/test/kotlin/org/http4k/webdriver/Http4kWebDriverFormTest.kt, http4k-testing/webdriver/src/test/resources/test.html
fix for regression where form fields with multiple values associated only sent a single value
=> Http4kWebDriver - fix for form field regression

http4k-core/src/main/kotlin/org/http4k/filter/Gzip.kt, http4k-core/src/test/kotlin/org/http4k/filter/ClientFiltersTest.kt, http4k-core/src/test/kotlin/org/http4k/filter/ServerFiltersTest.kt
I'm ok to get a push back on this, but we discovered for our streaming functionality, that gzip filter by default buffers everything in memory. We can just pass streaming for all routes... But we decided to implement a similar functionality in our code - to decide the mode for each request based on the body given.
Also it feels like this can be the default option.
=> Gzip mixed compression mode

core/format/kondor-json/src/main/kotlin/org/http4k/format/JBiDiMappingValues.kt, core/format/kondor-json/src/test/kotlin/org/http4k/format/KondorJsonAutoMarshallingJsonTest.kt, versions.properties
updated JBiDiMapping to work with latest Kondor-Json version (3.4.1)
=> updating JBiDiMapping to Kondor 3.4.1

core/format/kondor-json/src/main/kotlin/org/http4k/format/JBiDiMappingValues.kt, versions.properties
Simplified and updated JBiDiMapping for numbers to Kondor 3.4.2
=> updating JBiDiMapping to Kondor 3.4.2

core/core/src/main/kotlin/org/http4k/core/Status.kt
Would be nice to be able to use these ranges in a `when` statement.
=> Make status int ranges public
